### ISSUE TITLE
[bug] Can't connect in Trust Wallet browser

### ISSUE THREAD

**Issue by Trynight** [reown-com/appkit#1048]
### Link to minimal reproducible example

https://deelance.com/

### Summary

Hello! 

If you use the native browser (chrome/firefox) on mobile and use deeplink to connect in Trust Wallet, everything is fine and dapp works well.

Video:

https://github.com/WalletConnect/web3modal/assets/58222452/ed52a7df-c432-4ded-98af-e12c0ffe5fec

While, if you use the browser inside TrustWallet, you can't connect to the dapp.. nothing to do with it.. and we notice that is not happening to everyone but only to few Android users.

https://github.com/WalletConnect/web3modal/assets/58222452/2add7633-86c8-4d15-8ea3-9258309d22ff

### List of related npm package versions

    "wagmi": "^1.1.0"
    "viem": "^0.3.50",
    
    We tested with both version of web3modal 2.4.2 and 2.4.3

**Comment by 0xAsimetriq** [comment]
@Trynight we made a bunch of improvements in latest wagmi and web3modal packages, can you let me know if this issue still occurs? If it does, it's likely something specific to Trust (are you on their wallets latest version)?

**Comment by crosschainer** [comment]
same here

**Comment by meri-maki** [comment]
Has this issue been resolved? (also cannot send transactions when connected to trust via wc)
seems like it's an issue with Trust Wallet but support on their side says it's 'nothing they can do'
https://community.trustwallet.com/t/wallet-connect-trust-wallet-connection-issues/756942/12

**Comment by meri-maki** [comment]
For me with wagmi 1.3.8 it's still not working (updating wagmi to and viem to latest didn't help)
https://github.com/meri-maki/wagmi-issue

https://wagmi-issue.vercel.app/

https://github.com/WalletConnect/web3modal/assets/97887955/5405b6d0-c57f-4448-96af-46fe643f4bcb

**Comment by surya-signature** [comment]
For me the connection is loss after reload or reopen the application in trust wallet mobile app.In desktop browser extension the connection is not loss in trust wallet
