### ISSUE TITLE
[bug] web3modal not showing connection errors

### ISSUE THREAD

**Issue by arein** [reown-com/appkit#1336]
### Link to minimal reproducible example

https://hackers.gm.walletconnect.com/

### Summary

Web3modal is unable to connect to the Relay but still shows a QR code. This is really bad as end-users will not actually be able to connect.

<img width="685" alt="Screenshot 2023-09-15 at 10 59 09 AM" src="https://github.com/WalletConnect/web3modal/assets/966091/f987992b-49a2-4c74-87e4-3a6b7c5640bb">
<img width="1462" alt="Screenshot 2023-09-15 at 10 59 37 AM" src="https://github.com/WalletConnect/web3modal/assets/966091/3ba0a160-fa5f-4eb6-ba53-78b41a63ca5e">

### List of related npm package versions

Latest

**Comment by glitch-txs** [comment]
Adding some considerations:

https://github.com/orgs/WalletConnect/discussions/3719

**Comment by arein** [comment]
Also found this in https://github.com/WalletConnect/web-examples/issues/330

**Comment by arein** [comment]
![Uploading Screenshot 2024-06-22 at 3.41.45 PM.png…]()

**Comment by rtomas** [comment]
The problem seems to be solved. May I close the issue?
cc @arein
