### ISSUE TITLE
[bug] The web3model css is faulty

### ISSUE THREAD

**Issue by EV-Ain** [reown-com/appkit#1485]
### Link to minimal reproducible example

as shown in the figure

### Summary

![1700299422621](https://github.com/WalletConnect/web3modal/assets/101503420/fc7059d3-dcb7-4c25-a7cc-ef494197e3d9)
![Snipaste_2023-11-18_17-25-01](https://github.com/WalletConnect/web3modal/assets/101503420/95423f8e-284a-4e26-a8c2-baf832f74b84)

### List of related npm package versions

 @wagmi/core": "^1.4.6",
    "@web3modal/wagmi": "^3.3.1",
    "viem": "^1.19.1",
    "vue": "^3.3.4"

**Comment by glitch-txs** [comment]
what's wrong with it? it's scrollable

**Comment by EV-Ain** [comment]
> what's wrong with it? it's scrollable

the reason is html fontsize:52px

**Comment by EV-Ain** [comment]
How to solve this problem

**Comment by EV-Ain** [comment]
> what's wrong with it? it's scrollable

**Comment by EV-Ain** [comment]
> what's wrong with it? it's scrollable

How to solve this problem？

**Comment by EV-Ain** [comment]
> what's wrong with it? it's scrollable
look input box!

**Comment by 0xAsimetriq** [comment]
Which browser / version are you seeing this on?

**Comment by EV-Ain** [comment]
chrome



发自我的iPhone


------------------ Original ------------------
From: 0xAsimetriq ***@***.***&gt;
Date: Mon,Nov 20,2023 10:21 PM
To: WalletConnect/web3modal ***@***.***&gt;
Cc: EV-Ain ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [WalletConnect/web3modal] [bug] The web3model css is faulty(Issue #1485)





 
Which browser / version are you seeing this on?

**Comment by EV-Ain** [comment]
Chrome

------------------ Original ------------------
From: 0xAsimetriq ***@***.***&gt;
Date: Mon,Nov 20,2023 10:21 PM
To: WalletConnect/web3modal ***@***.***&gt;
Cc: EV-Ain ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [WalletConnect/web3modal] [bug] The web3model css is faulty(Issue #1485)





 
Which browser / version are you seeing this on?

**Comment by 0xAsimetriq** [comment]
Version, operatings system as well please.

**Comment by EV-Ain** [comment]
the reason is html fontsize:52px
look code！


------------------ Original ------------------
From: 0xAsimetriq ***@***.***&gt;
Date: Mon,Nov 20,2023 10:29 PM
To: WalletConnect/web3modal ***@***.***&gt;
Cc: EV-Ain ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [WalletConnect/web3modal] [bug] The web3model css is faulty(Issue #1485)





 
Version, operatings system as well please.

**Comment by EV-Ain** [comment]
> YEP, able to reproduce by just adding
> 
> body{
> 
>   font-size: 50px;
> 
> }
> 
> 
> 
> it also adds some "margin" on other elements, seems to be related to css more than the modal

Other styles do not have this problem. Will the later version fix this problem？
