### ISSUE TITLE
[bug]  DOMException: Permission denied to access property Symbol.iterator on cross-origin object

### ISSUE THREAD

**Issue by Trynight** [reown-com/appkit#1496]
### Summary

Hi guys, I noticed that if I use the custom wagmi configuration as per the web3modal documentation, I have a problem when I go to click the button to connect.

I have to click it twice and the first time I get this:

"DOMException: Permission denied to access property Symbol.iterator on cross-origin object"

While if I use the defaultWagmiConfing.. version everything works (this double click error disappears) but I don't have the possibility to insert my Infura api key and therefore forced to use the public ones

### List of related npm package versions

    "@wagmi/core": "^1.4.7",
    "@web3modal/wagmi": "^3.3.2",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "i18next": "^22.4.9",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-locize-backend": "^6.2.1",
    "locize": "^2.4.5",
    "locize-cli": "^7.13.2",
    "locize-lastused": "^3.2.2",
    "path-to-regexp": "^6.2.1",
    "react": "^18.2.0",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dom": "^18.2.0",
    "react-fast-marquee": "^1.6.2",
    "react-i18next": "^12.3.1",
    "react-icons": "^4.12.0",
    "react-lines-ellipsis": "^0.15.4",
    "react-router-dom": "^6.18.0",
    "react-scroll": "^1.9.0",
    "react-toastify": "^9.1.3",
    "swiper": "^11.0.4",
    "tailwind-merge": "^2.0.0",
    "viem": "^1.19.5",
    "vite-jsconfig-paths": "^2.0.1",
    "wagmi": "^1.4.7",

**Comment by schystz** [comment]
I'm having the same issue even without wagmi. How'd you fix it @Trynight?
