### ISSUE TITLE
Allow to skip rpc calls for balance / ens (v3-4)

### ISSUE THREAD

**Issue by iuriiiurevich** [reown-com/appkit#1888]
### What problem does this new feature solve?

In v2 there was the [`enableAccountView`](https://docs.walletconnect.com/web3modal/v2/javascript/wagmi/options#enableaccountview-optional) config option which could be set to `false` to prevent ens/balance calls from being made when a wallet is connected if there was no need for them (e.g. the Account view is not intended to be shown)

The problem is described in detail here: https://github.com/WalletConnect/web3modal/issues/824

### Describe the solution you'd like

A similar flag will do

**Comment by glitch-txs** [comment]
If you're still experiencing this issue please create a new one as we have integrated a new ticketing system, thanks!

**Comment by Victor-Salomon** [comment]
@glitch-txs Hello, I'm following up on this currently closed issue. I can't find any reliable solution. I understand it used to exist but not anymore right? 

I'm persisting the connection in my cookies as explained in the Nextjs documentation. Once it fetches the stored user, it also fetches its ens name and throws an error in the console when the user does not own one. 

Is there a way to prevent this? 

Let me know if you need me to provide more or a different way. 

<img width="667" alt="image" src="https://github.com/user-attachments/assets/62a3b312-c325-46db-92b8-d47d1cd62d94">

**Comment by rtomas** [comment]
this is not longer an issue.
