### ISSUE TITLE
[bug] Web3Modal + Wagmi : zkSync's EIP712 paymaster transactions are not supported on mobile

### ISSUE THREAD

**Issue by NilsDelage** [reown-com/appkit#2035]
### Link to minimal reproducible example

[https://github.com/NilsDelage/tests-paymaster-w3m-wevm](https://github.com/NilsDelage/tests-paymaster-w3m-wevm)

### Summary

Steps to reproduce:

* launch app
* connect on mobile (either via injected connexion or via wallet connect)
* click "send Transaction", eip712 signing window appears in your wallet
* sign, no transaction is sent
* disconnect and reconnect with a browser wallet
* click "send transaction", window appears
* sign, transaction is broadcasted to zkSync

Additionally, different mobile wallets, throw different errors:

* Zerion mobile: no error thrown, transaction is not sent.
* TrustWallet mobile:

```
{context: 'client'}context: "client"[[Prototype]]: Object 'Missing or invalid. request() method: eth_sendRawTransaction'
page.tsx:77 error TransactionExecutionError: An unknown RPC error occurred.
```

* Metamask mobile:

```
 '{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32600,"message":"Invalid request"}}'
 page.tsx:77 error TransactionExecutionError: User rejected the request.
```

We extend Wagmi's wallet client with Viem's [eip712WalletActions](https://viem.sh/zksync) to propose those sponsored transactions.

### List of related npm package versions

```
"@web3modal/wagmi": "^4.0.13",
"viem": "^2.7.20",
"wagmi": "^2.5.7",
"@tanstack/react-query": "^5.25.0"
```

**Comment by glitch-txs** [comment]
Hi, are you still experiencing this issue in the latest version of Wagmi and Web3Modal?

**Comment by NilsDelage** [comment]
Hi, the metamask mobile version is now working when using the internal browser, but not working through wallet connect.
In fact, it seems that this is the issue, all connections using wallet-connect are not able to handle paymaster transactions.
You can test the example with several wallets at https://vercel.com/nils-projects-70c69f79/tests-paymaster-w3m-wevm

**Comment by glitch-txs** [comment]
cc @Sam-Newman

**Comment by NilsDelage** [comment]
Hi, the metamask mobile version is now also working when using wallet connect, but other mobile wallets which work with the integrated browser do not work when using Wallet Connect. 
Thus, it seems possible to have wallets supporting `eth_sendRawTransaction` through Wallet Connect, but requires some work on the wallet's side.

It seems like it is not a problem from the library, I am closing this issue.
