### ISSUE TITLE
[bug] the wallet options doesn't show up in chrome mobile

### ISSUE THREAD

**Issue by sdrhashemi** [reown-com/appkit#2176]
### Link to minimal reproducible example

https://github.com/FishDontExist/pancakeSwapLikeWalletConnect

### Summary

I just created a react-app and implemented the latest Web3modal based on the official docs, but when I tested the app on my chrome mobile, the wallet connection options doesn't appear on the modal.
![web3modalBugReport](https://github.com/WalletConnect/web3modal/assets/107583285/4c634378-c7ab-459c-ac6f-9cc2ca0fcc89)

### List of related npm package versions

  "@tanstack/react-query": "^5.29.2",
    "@web3modal/wagmi": "^4.1.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "^2.9.23",
    "wagmi": "^2.5.20"
  },
"devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^7.2.0",
    "@typescript-eslint/parser": "^7.2.0",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "typescript": "^5.2.2",
    "vite": "^5.2.0"
  }

**Comment by glitch-txs** [comment]
I cloned your repo and it works well for me. Is it possible that you're using a different project ID?

![IMG_20240422_185911.jpg](https://github.com/WalletConnect/web3modal/assets/66949816/0beb4e91-c994-4a21-a82e-47455c4acab7)

**Comment by glitch-txs** [comment]
I'm not able to repro, do you see any errors on console?

**Comment by glitch-txs** [comment]
weird, can you try here: https://lab.web3modal.com/library/wagmi/

**Comment by FishDontExist** [comment]
> weird, can you try here: https://lab.web3modal.com/library/wagmi/

Thanks mate :)

**Comment by Sam-Newman** [comment]
@FishDontExist Sounds like this is resolved from your side?
I will close it but please re-open if required.
