### ISSUE TITLE
[bug] Disconnect gives error while SDK is still loading

### ISSUE THREAD

**Issue by chris13524** [reown-com/appkit#2348]
### Link to minimal reproducible example

lab.web3modal.com

### Summary

If you connect your wallet and then refresh the page, there is a period of time where clicking disconnect will throw an error

[Video reproduction](https://walletconnect.slack.com/archives/C03RVH94K5K/p1717327968039519)

### List of related npm package versions

latest

**Comment by rtomas** [comment]
Is this still happening? I cannot reproduce it.

**Comment by chris13524** [comment]
Looks like this may be fixed in latest version. Closing for now

**Comment by chris13524** [comment]
Not to my knowledge; closing
