### ISSUE TITLE
[bug] Frame wallet not detected by Web3Modal

### ISSUE THREAD

**Issue by yvaskov** [reown-com/appkit#2363]
### Link to minimal reproducible example

Can be reproduced on [https://eth.blockscout.com/](https://eth.blockscout.com/)<br>UPDATED: 28-AUG<br>tested with [https://lab.web3modal.com/library/wagmi/](https://lab.web3modal.com/library/wagmi/)

### Summary

WC modal does not detect `Frame` wallet running as:

* Frame desktop [app](https://github.com/floating/frame/releases/tag/v0.6.9)
* Frame Companion [extension](https://chromewebstore.google.com/detail/frame-companion/ldcoohedfbjoobcadoglnnmmfbdlmmhf)

### Tested on

MacOS Sonoma 14.5, Apple Silicon
Safari Version 17.5 (19618.2.12.11.6)
Chrome Version 125.0.6422.141 (Official Build) (arm64)

### Steps to reproduce

1. Run Frame app with an active account
2. (optional) Enable Frame Companion extension in Chrome
3. Open [https://eth.blockscout.com/](https://eth.blockscout.com/)
4. Click on `Connect wallet`
5. Select `All wallets`
6. Select `Frame`

Result: Not Detected

![image](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/e9aea199-30cf-4c31-85b3-7c771b84258a/f81fd3fd-4954-4158-829a-d3695c57a587?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9lOWFlYTE5OS0zMGNmLTRjMzEtODViMy03Yzc3MWI4NDI1OGEvZjgxZmQzZmQtNDk1NC00MTU4LTgyOWEtZDM2OTVjNTdhNTg3IiwiaWF0IjoxNzI0ODQ4ODE5LCJleHAiOjMzMjk1NDA4ODE5fQ.GmyPTbuN7STiB3rgFACc81wGQ7DTQ3bWDv_zFxRWWxY "=374x")

### List of related npm package versions

@web3modal/wagmi: 4.2.1<br><br>**UPDATED 28-AUG**

* the wallet is being detected

<img src="https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/92b526f0-05b4-4fb7-b859-ad5d8c8fe53d/f6515ee7-b5d3-4ec6-8e37-57a35110d727?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS85MmI1MjZmMC0wNWI0LTRmYjctYjg1OS1hZDVkOGM4ZmU1M2QvZjY1MTVlZTctYjVkMy00ZWM2LThlMzctNTdhMzUxMTBkNzI3IiwiaWF0IjoxNzI0ODQ4ODE5LCJleHAiOjMzMjk1NDA4ODE5fQ.qWBPMP28mD5kLDn6wrb1fj19XczW6mKS2gDHZXRr760 " alt="image.png" width="396" height="414" />

* When I try to connect this msg appears

<img src="https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/f784de73-455e-4cfb-a991-55a56e49d5c0/f943e195-3def-4c6e-8214-1e81c6d910d3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9mNzg0ZGU3My00NTVlLTRjZmItYTk5MS01NWE1NmU0OWQ1YzAvZjk0M2UxOTUtM2RlZi00YzZlLTgyMTQtMWU4MWM2ZDkxMGQzIiwiaWF0IjoxNzI0ODQ4ODE5LCJleHAiOjMzMjk1NDA4ODE5fQ._RnyJ6lzOlqdBlS4PJlDNL-g1YpIJHUaCA7BdtccCVs " alt="image.png" width="405" height="386" />

**Comment by rtomas** [comment]
Issue has been canceled
