### ISSUE TITLE
[bug] MetaMask logo is cropped

### ISSUE THREAD

**Issue by chris13524** [reown-com/appkit#2372]
### Link to minimal reproducible example

https://lab.web3modal.com/library/wagmi-all/

### Summary

<img width="123" alt="image" src="https://github.com/WalletConnect/web3modal/assets/1979423/0c7d8c9d-0b5e-4801-80c6-314705724aff">

This was part of https://github.com/WalletConnect/web3modal/issues/2134 but that issue was closed so re-opening here

### List of related npm package versions

latest

**Comment by arein** [comment]
this was fixed
