### ISSUE TITLE
[bug] OKX "Webapp" link leads to 404 page

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [reown-com/appkit#2577]
### Link to minimal reproducible example

https://github.com/Doko-Demo-Doa/w3m-wagmi-bug-demo

### Summary

- Access the app in a browser that HAS NO OKX wallet installed: https://w3m-wagmi-bug-demo.vercel.app/
- Click on "All Wallets"
- Choose "OKX Wallet"
- Click on "Webapp"
- Click on "Open" button below the text "Open and continue in a new browser tab"
- The browser redirects to a dead link that starts with `https://www.okx.com/download/wc?uri=`

### List of related npm package versions

```
  "dependencies": {
    "@tanstack/react-query": "^5.51.11",
    "@web3modal/wagmi": "^5.0.7",
    "next": "14.2.5",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.17.9",
    "wagmi": "^2.11.3"
  },
 ```

**Comment by rtomas** [comment]
closing it .. please reopen if you continue with the issue @Doko-Demo-Doa
