### ISSUE TITLE
[bug] No response when connecting to phantom wallet

### ISSUE THREAD

**Issue by leslie555** [reown-com/appkit#2684]
### Link to minimal reproducible example

https://web.telegram.org/k/#@leslie_57_bot

### Summary

**The code repo: https://github.com/leslie555/TG-mini-app**

I am trying to develop a telegram mini app, and I want to connect the phantom wallet in my mini app, so I followed [the tutorial](https://docs.walletconnect.com/appkit/react/core/installation?platform=wagmi) to install `@web3modal/wagmi`.
After I clicked the Connect Button, the wallet list showed that phantom was installed (chrome extension in my case). But after I selected phantom, the phantom extension did not respond. If I selected metamask, I could connect the wallet normally.
![image](https://github.com/user-attachments/assets/82eb146b-0bfa-4d2c-bf77-f102123836b3)

### List of related npm package versions

"@web3modal/wagmi": "^5.0.11",
"viem": "^2.19.2",
"wagmi": "^2.12.4",
"@tanstack/react-query": "^5.51.21",

**Comment by alanwu4321** [comment]
same issue
