### ISSUE TITLE
[bug] TypeError: Cannot read properties of undefined (reading 'Buffer') when dockerizing

### ISSUE THREAD

**Issue by stratusceo** [reown-com/appkit#2701]
### Link to minimal reproducible example

NDA

### Summary

When I dockerize a project with :
- "@web3modal/wagmi": "^5.0.11",
- "wagmi": "^2.12.4",

I then open the website (which opens well), then stops on loading step because of this issue.
<img width="992" alt="Screenshot 2024-08-14 at 2 38 25 PM" src="https://github.com/user-attachments/assets/423345b1-9158-46af-9ff0-a7b6cf4ca45f">
<img width="990" alt="Screenshot 2024-08-14 at 2 40 51 PM" src="https://github.com/user-attachments/assets/8fbe6ffd-d5d7-4fc6-8468-6cab186dd464">

NB: I don't have the issue if I remove **@web3modal/wagmi** in package.json.

Many thanks for your help!

### List of related npm package versions

- "@web3modal/wagmi": "^5.0.11",
- "wagmi": "^2.12.4",

**Comment by rtomas** [comment]
i cannot reproduce it
