### ISSUE TITLE
[bug] TypeError: Failed to resolve module specifier '..-node_modules-@web3modal-ui-dist-esm-index.CfY9nOUx.js'

### ISSUE THREAD

**Issue by danialj** [reown-com/appkit#2755]
### Link to minimal reproducible example

npm run build:h5, prompt failed to resolve module

### Summary

when i run : npm run build:h5, build complete. then i upload to web server. when i run in chrome, the console prompt error:
TypeError: Failed to resolve module specifier '..-node_modules-@web3modal-ui-dist-esm-index.CfY9nOUx.js' in client.js.
the client.js file is: @web3modal/scaffold/dist/esm/src/client.js.

how can i resolve this problem?
thanks very much.

### List of related npm package versions

"@web3modal/ethers": "5.1.1"

**Comment by rtomas** [comment]
Can you share with us a minimal reproducible example ?
