### ISSUE TITLE
[bug] v5.1.6

### ISSUE THREAD

**Issue by songjiazhun** [reown-com/appkit#2803]
### Link to minimal reproducible example

  yarn add @web3modal/ethers5@5.1.6

### Summary

![9066c88a-68c5-4f27-b82f-8341be118ca2](https://github.com/user-attachments/assets/02596989-56c6-47d0-88c6-af4422c4a159)

### List of related npm package versions

yarn add @web3modal/ethers5@5.1.6
```[tasklist]
### Tasks
```

**Comment by rtomas** [comment]
hi @songjiazhun 
can you share a minimal reproducible example ? are you using vue ?

**Comment by songjiazhun** [comment]
No, react

**Comment by songjiazhun** [comment]
![20240906-183712](https://github.com/user-attachments/assets/50b17ebd-081e-4852-9353-b57d4b8cea98)
hi, Tomas Rawski, 图片上红色标识的地方，是插件编译不过的原因

**Comment by songjiazhun** [comment]
![1a5ea4b9-9227-4b75-b038-571b276ba4e6](https://github.com/user-attachments/assets/e9b65057-2645-4f5b-925c-ed307dee3767)
https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal/react-ethersv5 ,报一样的错误

**Comment by rtomas** [comment]
Yes. We are having problems with vue and ethers. Please use 5.1.2 until we release a fix.
