### ISSUE TITLE
[bug] vue3 

### ISSUE THREAD

**Issue by bridgerl** [reown-com/appkit#2817]
### Link to minimal reproducible example

Create a new vue3ts project and add dependencies

### Summary

![image](https://github.com/user-attachments/assets/8c1b9fd3-d04a-4055-be77-406aaeb0cae5)
![image](https://github.com/user-attachments/assets/3ca7dc00-2fce-49dd-aaa3-3d15de4f9752)

### List of related npm package versions

"@web3modal/ethers5": "^5.1.2",

**Comment by rtomas** [comment]
we are aware about this issue ... please use v5.1.2 

https://linear.app/walletconnect/issue/APKT-1040/[bug]-cant-build-ethers5-latest-version-using-vue-since-v513

**Comment by rtomas** [comment]
fixed in latest version
