### ISSUE TITLE
[bug] During SIWE, the 'Sign' Button is not disabled in 'processing' state. Multiple clicks cause multiple sign requests 

### ISSUE THREAD

**Issue by mprouve** [reown-com/appkit#2841]
### Link to minimal reproducible example

none

### Summary

During the SIWE flow, once the 'sign' page of the web3modal comes up and a user clicks 'sign', the relevant connector confirmation window pops up. However, the sign button has a circular progress icon and is still clickable, resulting in multiple sign requests.

https://github.com/user-attachments/assets/79cde95b-dda8-4312-98f4-670aa5c5d690

### List of related npm package versions

@web3modal/siwe: 5.1.7
@web3modal/wagmi: 5.1.7

**Comment by rtomas** [comment]
solved in latest version
