### ISSUE TITLE
[bug] Phantom Wallet does not prompt to connect when the web app is embedded in an iframe

### ISSUE THREAD

**Issue by andremfaria** [reown-com/appkit#2845]
### Link to minimal reproducible example

https://github.com/andremfaria/web3modal-phantom-iframe

### Summary

**Current behaviour:** 
Phantom Wallet does not prompt when the web app is embedded in an iFrame. We get stuck in an infinite load.  

**Expect behaviour:** 
Phantom Wallet should prompt the user to connect. 

**Evidence:** 

https://github.com/user-attachments/assets/e539511a-5b7f-499e-97ef-d258da55c7c3

**Note**: In the actual project, both the parent and the embedded web app are hosted under the same domain.

### List of related npm package versions

    "@web3modal/solana": "5.1.7",
    "@tanstack/react-query": "5.24.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "vite": "5.2.11",
    "@solana/wallet-adapter-backpack": "0.1.14",
    "@solana/wallet-adapter-wallets": "0.19.32"

**Comment by rtomas** [comment]
It's working in the latest version; I've just tested it.

**Comment by ralphking** [comment]
Phantom likely never work in an iFrame, they do not inject the provider: https://docs.phantom.com/solana/detecting-the-provider
