### ISSUE TITLE
[bug] EstimateGas in Ether6 Adapter

### ISSUE THREAD

**Issue by Tom-Krnl** [reown-com/appkit#2847]
### Link to minimal reproducible example

-

### Summary

Hi, i writing you in case of EstimateGas issue for Ether6 Adapter

when user try to execute contract that not able to estimate, the current behavior should be like this when they use wallet as MetaMask

Expected Behaviors
![image](https://github.com/user-attachments/assets/ab4476eb-006f-4c2c-b7e8-a6e8c54395a7)

Current
but now it seem the adapter for ether6 will be throw err,

![image](https://github.com/user-attachments/assets/888304a6-f9eb-412e-9af7-5dfe4e8cb190)

i suspect the problem come from Adapter [ main/packages/base/adapters/evm/ethers/client.ts ](https://github.com/WalletConnect/web3modal/blob/main/packages/base/adapters/evm/ethers/client.ts#L417)

### List of related npm package versions

Ether6, Web3Modal (Latest)

**Comment by rtomas** [comment]
its working on latest
