### ISSUE TITLE
[bug] WagmiAdapter: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by alanwu4321** [reown-com/appkit#2862]
### Link to minimal reproducible example

https://docs.reown.com/appkit/next/core/installation

### Summary

After `create-next-app` and following the exact instructions on https://docs.reown.com/appkit/next/core/installation

 I kept getting TypeError: Cannot read properties of undefined (reading 'id') on the line `new WagmiAdapter({`
    
<img width="991" alt="image" src="https://github.com/user-attachments/assets/0b0f65cf-3770-4a4d-949c-0baa98f33b75">

### List of related npm package versions

```
  "dependencies": {
    "@reown/appkit-adapter-wagmi": "^1.0.1",
    "@reown/appkit-core": "^1.0.1",
    "@tanstack/react-query": "^5.56.2",
    "@wagmi/core": "^2.13.5",
    "networks": "link:@reown/appkit/networks",
    "next": "14.2.11",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.21.8",
    "wagmi": "^2.12.12"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.11",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
  ```

**Comment by 0xprincedev** [comment]
Did you find a way to fix that?
@alanwu4321

**Comment by abdullahmehboob20s** [comment]
Same error. Using react router v7

**Comment by baixiaoyu2997** [comment]
same issue
