### ISSUE TITLE
[docs] Vue examples are using React?

### ISSUE THREAD

**Issue by scholtz** [reown-com/appkit#2869]
### Summary

At the website https://docs.reown.com/appkit/vue/core/installation#smart-contract-interaction in section Smart Contract Interaction under Ethers its using the react library instead of the vuejs library.. 

Where is migration guide from @web3modal/ethers/vue ?

### Link to the related docs page

https://docs.reown.com/appkit/vue/core/installation

**Comment by rtomas** [comment]
hi @scholtz , you are right. We will fix it as soon as possible.

**Comment by rtomas** [comment]
docs are fixed
