### ISSUE TITLE
[docs] In the Ethers example, the snipet has an error when calling "useAppKitProvider"

### ISSUE THREAD

**Issue by ultraKelevra** [reown-com/appkit#2871]
### Summary

useAppKitProvider() asks for a chain name space. And it is being called without params in the example.

The [Implementation](https://docs.reown.com/appkit/vue/core/installation#implementation) section has a mistake.
The "ethersAdapter" is never instantiated to be fed into "createAppKit()" call.

### Link to the related docs page

https://docs.reown.com/appkit/vue/core/installation#smart-contract-interaction

**Comment by prabhatkashyap902** [comment]
yes, they have done spellings error
import { Ethers5Adapter } from '@reown/appkit-adapters-ethers'
here it should be 
import { EthersAdapter } from '@reown/appkit-adapter-ethers'

**Comment by DaveTheFrontEndDev** [comment]
@prabhatkashyap902 I think what @ultraKelevra is referring to is this 
![Screenshot 2024-10-09 at 11 23 38](https://github.com/user-attachments/assets/ffc9bdf4-8e95-4eb5-a005-ed4aaf0c4360)
Whereas the [documentation](https://docs.reown.com/appkit/react/core/installation) show this without any parameters.
![Screenshot 2024-10-09 at 11 25 13](https://github.com/user-attachments/assets/aa2aa72e-28f4-4acc-b1c6-d5d47bedba4c)

**Comment by rtomas** [comment]
PR -> https://github.com/reown-com/reown-docs/pull/97
