### ISSUE TITLE
[bug] Is the current version of solana unavailable?

### ISSUE THREAD

**Issue by SuperJiZheng** [reown-com/appkit#2902]
### Link to minimal reproducible example

import { solana, solanaTestnet, solanaDevnet } from '@reown/appkit/networks' import {   createAppKit,   useAppKit,   useAppKitEvents,   useAppKitState,   useAppKitTheme } from '@reown/appkit/vue' import { BackpackWalletAdapter } from '@solana/wallet-adapter-backpack' import {   PhantomWalletAdapter,   HuobiWalletAdapter,   SolflareWalletAdapter,   TrustWalletAdapter } from '@solana/wallet-adapter-wallets'

### Summary

import { solana, solanaTestnet, solanaDevnet } from '@reown/appkit/networks'
import {
  createAppKit,
  useAppKit,
  useAppKitEvents,
  useAppKitState,
  useAppKitTheme
} from '@reown/appkit/vue'
import { BackpackWalletAdapter } from '@solana/wallet-adapter-backpack'
import {
  PhantomWalletAdapter,
  HuobiWalletAdapter,
  SolflareWalletAdapter,
  TrustWalletAdapter
} from '@solana/wallet-adapter-wallets'

**These files are not in node_modules**

### List of related npm package versions

npm install @reown/appkit @reown/appkit-adapter-solana
examples/vue-solana/src/App.vue

**Comment by rtomas** [comment]
please check our vue docs ... nowadays are great :)

https://docs.reown.com/appkit/vue/core/installation
