### ISSUE TITLE
[bug] Polygon Amoy is not available after updating to appkit.

### ISSUE THREAD

**Issue by stinso** [reown-com/appkit#2906]
### Link to minimal reproducible example

noLink

### Summary

After updating from web3modal to appkit the polygon amoy testnet is not available anymore. Is it possible to add it manually?

### List of related npm package versions

"@reown/appkit": "^1.0.3",
"@reown/appkit-adapter-wagmi": "^1.0.3",
"wagmi": "^2.12.13"

**Comment by stinso** [comment]
`const polygonAmoy = {
  id: 'eip155:80002',
  chainId: 80002,
  name: 'Polygon Amoy',
  currency: 'MATIC',
  explorerUrl: 'https://amoy.polygonscan.com',
  rpcUrl: 'https://rpc.walletconnect.org/v1/?chainId=eip155:80002',
  chainNamespace: 'eip155',
}`

**Comment by stinso** [comment]
Seems like adding it manually works. But can I be sure that the rpcUrl stays alive?

```
const polygonAmoy = {
  id: 'eip155:80002',
  chainId: 80002,
  name: 'Polygon Amoy',
  currency: 'MATIC',
  explorerUrl: 'https://amoy.polygonscan.com',
  rpcUrl: 'https://rpc.walletconnect.org/v1/?chainId=eip155:80002',
  chainNamespace: 'eip155',
}
```

**Comment by 2facedsquid** [comment]
would be nice to have this out of the box, since other testnets like sepolia and sepoliaBase are supported

**Comment by rtomas** [comment]
Thanks, we are working to improve the usage of networks

**Comment by tawago** [comment]
I've encountered the same issue. Would be nice if major testnets are covered.

**Comment by rtomas** [comment]
please update to latest or check docs for new information about how we are managing the networks -> https://docs.reown.com/appkit/react/core/custom-networks
