### ISSUE TITLE
[bug] unable to set custom RPCs, RPCs are overwritten with wallet connect RPCs

### ISSUE THREAD

**Issue by kevtechi** [reown-com/appkit#2910]
### Link to minimal reproducible example

https://github.com/techi-solutions/soliditree/blob/main/services/walletConnect/config/index.ts

### Summary

I expect to be able to use my own RPCs without the library overwriting the provided links. Providing custom transport urls, chains or networks don't seem to do anything.

The documentation on this seems to be lacking.

If I am mistaken and this is indeed possible, how can this be achieved? It's a basic requirement of web3 development.

### List of related npm package versions

latest

**Comment by coderodigital** [comment]
I am attaching my issue here, too, which should have very high priority.

**Comment by coderodigital** [comment]
https://github.com/reown-com/appkit/issues/3056
