### ISSUE TITLE
[bug] SSR Flag in `WagmiAdapter` fails to work as expected in Next.js

### ISSUE THREAD

**Issue by 0xonerb** [reown-com/appkit#2940]
### Link to minimal reproducible example

https://github.com/0xonerb/next-reown-appkit-ssr

### Summary

When attempting to use the `ssr: true` option in the `WagmiAdapter` configuration, the expected behavior of delaying the store's hydration to avoid hydration mismatch errors in Next.js is not functioning as intended.

![Screenshot from 2024-09-26 11-04-00](https://github.com/user-attachments/assets/d66d20d5-a5fb-42bb-a552-ab597bb2e526)
![Screenshot from 2024-09-26 11-03-54](https://github.com/user-attachments/assets/ffc590af-60e3-4e7e-94ce-25ff2599def5)

```ts
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({
    storage: cookieStorage
  }),
  ssr: true,
  projectId,
  networks
})
```

This configuration doesn't seem to take effect. To resolve the issue, I had to manually create a new Wagmi config using `createConfig` and override the default `wagmiConfig` from `wagmiAdapter`:

```ts
export const newWagmiConfig = createConfig({
  chains,
  transports: {
    [mainnetChain.id]: http(),
    [arbitrumChain.id]: http()
  },
  ssr: true,
  storage: createStorage({
    storage: cookieStorage
  })
});

wagmiAdapter.wagmiConfig = newWagmiConfig;
```

**Before:**

![Screenshot from 2024-09-26 11-04-14](https://github.com/user-attachments/assets/644bab9c-44c4-47f8-a2ec-a8a96777b172)

**After:**

![Screenshot from 2024-09-26 11-03-24](https://github.com/user-attachments/assets/c467b169-517a-4e8d-9bad-9e1abc5f4f02)

This manual override should not be necessary. It would be helpful to have the `ssr` option work directly within the `WagmiAdapter` configuration. Could this be looked into for a fix?

### List of related npm package versions

```
"dependencies": {
  "@reown/appkit": "^1.0.4",
  "@reown/appkit-adapter-wagmi": "^1.0.4",
  "@tanstack/react-query": "^5.56.2",
  "@wagmi/core": "^2.13.7",
  "next": "14.2.13",
  "react": "^18",
  "react-dom": "^18",
  "viem": "^2.21.15",
  "wagmi": "^2.12.14"
},
"devDependencies": {
  "@types/node": "^20",
  "@types/react": "^18",
  "@types/react-dom": "^18",
  "eslint": "^8",
  "eslint-config-next": "14.2.13",
  "postcss": "^8",
  "tailwindcss": "^3.4.1",
  "typescript": "^5"
}
```

**Comment by paintoshi** [comment]
@0xonerb Seen this too with next. Interesting workaround, could be useful until solved

**Comment by 0xonerb** [comment]
Hey @rtomas, can you please check this issue with the development team?

**Comment by rtomas** [comment]
https://linear.app/reown/issue/APKT-1223/[bug]-ssr-flag-in-wagmiadapter-fails-to-work-as-expected-in-nextjs
