### ISSUE TITLE
[bug] Modal does not change to Account view when connected

### ISSUE THREAD

**Issue by 0xonerb** [reown-com/appkit#2941]
### Link to minimal reproducible example

https://github.com/0xonerb/next-reown-appkit-email-social

### Summary

If I'm connecting to a wallet using Email or MetaMask and reload the page and click the "Connect Wallet" button, the "Connect" view modal opens and after connected it does not change to "Account". I need to close the modal and click on the address to see the "Account" modal:

https://github.com/user-attachments/assets/70a2d17b-e787-47df-8dea-b50301b24f0a

### List of related npm package versions

```
"dependencies": {
  "@reown/appkit": "^1.0.4",
  "@reown/appkit-adapter-wagmi": "^1.0.4",
  "@tanstack/react-query": "^5.56.2",
  "@wagmi/core": "^2.13.7",
  "next": "14.2.13",
  "react": "^18",
  "react-dom": "^18",
  "viem": "^2.21.15",
  "wagmi": "^2.12.14"
},
"devDependencies": {
  "@types/node": "^20",
  "@types/react": "^18",
  "@types/react-dom": "^18",
  "eslint": "^8",
  "eslint-config-next": "14.2.13",
  "postcss": "^8",
  "tailwindcss": "^3.4.1",
  "typescript": "^5"
}
```

**Comment by rtomas** [comment]
Internal : https://linear.app/reown/issue/APKT-1736/investigate-common-errors-with-google-social-login

**Comment by rtomas** [comment]
Note: Social logins are working despite this console errors.

**Comment by rtomas** [comment]
duplicated : https://github.com/reown-com/appkit/issues/2932
closing this
