### ISSUE TITLE
[bug] Unable to approve a transaction while logged in using gmail / social

### ISSUE THREAD

**Issue by 0xonerb** [reown-com/appkit#2942]
### Link to minimal reproducible example

N/A

### Summary

I'm integrating the `reown-com/appkit` wallet that allows users to log in using their email and get an associated address. However, when attempting to approve a transaction, an approval modal from AppKit appears. Unfortunately, when I click on the approve button, I get an error below:

The transaction works for me if I choose to connect MetaMask, but it doesn't work for me if I choose Gmail / social.

![Screenshot from 2024-09-26 12-20-51](https://github.com/user-attachments/assets/6fc6a8eb-de76-42eb-940b-36022159d8d7)
![Screenshot from 2024-09-26 12-20-29](https://github.com/user-attachments/assets/83853e8a-b731-4678-9eb7-328ec70f49b5)

### List of related npm package versions

```
"dependencies": {
  "@reown/appkit": "^1.0.4",
  "@reown/appkit-adapter-wagmi": "^1.0.4",
  "@tanstack/react-query": "^5.40.1",
  "@wagmi/core": "^2.13.4",
  "next": "^14.2.9",
  "react": "^18.3.1",
  "react-dom": "^18.3.1",
  "viem": "^2.21.2",
  "wagmi": "^2.12.8",
},
```

**Comment by rtomas** [comment]
Do you have minimal reproducible example ?

Our lab dApps are functioning well.
https://appkit-lab.reown.com/

**Comment by 0xonerb** [comment]
> Do you have minimal reproducible example ?

Hey @rtomas, i haven't... but it seems to be working fine now :+1:
