### ISSUE TITLE
[bug] Wallet Connect QR not shown after migrating from w3m to appKit

### ISSUE THREAD

**Issue by paintoshi** [reown-com/appkit#2951]
### Link to minimal reproducible example

https://github.com/paintoshi/appkit-demo-react-vite

### Summary

The WC QR worked fine with @web3modal/wagmi using react+vite+wagmi. Also connecting from chrome on iPhone using the metamask connection. It would switch to the MM app and connect.

With @reown/appkit and @reown/appkit-adapter-wagmi 1.0.4 it does not work. I'm hosting the app at the exact same verified domain using the same project ID.

The QR fails to load since it fails to verify it seems.

![image](https://github.com/user-attachments/assets/b1fb81f8-1629-4b51-b0d5-5178b33a9993)

![image](https://github.com/user-attachments/assets/1b550f77-e549-4424-b07d-9ba6b54218dc)

And on mobile chrome, clicking on metamask to connect just displays a retry button. It won't switch to metamask or even try. Likely related to same issue.

The reproducible demo won't work by itself since it needs to be hosted on a valid domain and I don't have that for this purpose, making it harder to prove the bug. I only have my main app which is huge and in a priv repo. Or maybe it actually should be working, I'm not sure what has changed with appKit. My old app does show the QR even when running on localhost.

I can see the QR works on https://reown.com/appkit so not sure what differs. Maybe it's whitelisted on Wallet Connect by default.

### List of related npm package versions

"@reown/appkit": "^1.0.4",
"@reown/appkit-adapter-wagmi": "^1.0.4",
"wagmi": "2.12.9",
"viem": "2.21.4",
"@tanstack/react-query": "^5.56.2",

**Comment by rtomas** [comment]
Please check our Reown AppKit examples to find what you are doing wrong.
https://github.com/reown-com/web-examples/tree/feat/create-appkit-examples/dapps/appkit
Also please try with the latest version.

**Comment by tonymfer** [comment]
bumping on this... after migrating from w3m to appKit, the same issue is happening on [https://mint.club](https://mint.club)
would much appreciate if you could have a check on this @rtomas 
![Screenshot 2024-10-28 at 20 08 21](https://github.com/user-attachments/assets/c57dd9a0-4c23-4e8b-b633-1371692977f2)

**Comment by paintoshi** [comment]
Looks like this issue has been resolved. Now using v1.5.2
