### ISSUE TITLE
[bug] Appkit not working with Nextjs anymore - { pino } import error

### ISSUE THREAD

**Issue by AnesBkdm** [reown-com/appkit#2980]
### Link to minimal reproducible example

https://github.com/AnesBkdm/appkit-not-working

### Summary

AppKit worked on our Nextjs project (we don't use App Router) just fine until yesterday. Nextjs now throws an import error even on fresh project installs. Reproduce via attached repo: https://github.com/AnesBkdm/appkit-not-working

```
SyntaxError: Named export 'pino' not found. The requested module '@walletconnect/logger' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@walletconnect/logger';
const { pino } = pkg;
```

<img width="978" alt="Screenshot 2024-10-02 at 09 07 37" src="https://github.com/user-attachments/assets/56194a21-c17e-435b-aec9-1f7e835759da">

The error suggests editing node_module files, which obviously is not ideal. Has anyone come across this issue?

### List of related npm package versions

```js
"dependencies": {
    "@reown/appkit": "^1.0.5",
    "@reown/appkit-adapter-wagmi": "^1.0.5",
    "@tanstack/react-query": "^5.56.2",
    "next": "14.1.0",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.21.16",
    "wagmi": "^2.12.16"
  },
```

**Comment by AnesBkdm** [comment]
I would like to add that this error is common on wagmi, ethers6 and ethers5 modes of Reown Appkit. We had to fallback to the old Web3Modal packages suggested in the dashboard to keep our web3 Login feature.

<img width="1361" alt="Screenshot 2024-10-02 at 09 26 16" src="https://github.com/user-attachments/assets/b91cd338-9870-410a-bd36-2f04cb399017">

**Comment by dms120** [comment]
I'm also struggling with this one.
