### ISSUE TITLE
[bug] Issue with useAccount hook status after closing AppKit modal

### ISSUE THREAD

**Issue by remibeaufils** [reown-com/appkit#2983]
### Link to minimal reproducible example

https://affc.wow.art/

### Summary

When using the AppKit modal to select a wallet provider that I don’t have installed (e.g., Rainbow Wallet) and then closing the AppKit modal, the `status` and `isConnecting` props from the `useAccount` hook (wagmi) remain at `"connecting"` and `true`. This behavior causes a bug in my app, which depends on these values being updated correctly.

I expect the `status` and `isConnecting` values to reset to `"disconnected"` and `false` after closing the modal, as they do when selecting MetaMask and closing it.

### List of related npm package versions

@reown/appkit@1.0.1
@reown/appkit-adapter-wagmi@1.0.1
@wagmi/connectors@5.1.11
@wagmi/core@2.13.5
wagmi@2.12.12

**Comment by rtomas** [comment]
I cannot reproduce is latest. 
https://appkit-web-examples-react-wagmi.vercel.app/
