### ISSUE TITLE
[bug]  Failed to deserialize query string (Phantom Solana)

### ISSUE THREAD

**Issue by Beor18** [reown-com/appkit#2987]
### Link to minimal reproducible example

https://drive.google.com/file/d/1xIRVEfOTM0DJmdrZb6qBNFv8HULhI131/view?usp=sharing

### Summary

I connect the Phantom wallet on Solana and receive the following message:

Error: 400: Failed to deserialize query string: missing field chainId

### List of related npm package versions

  "@reown/appkit": "^1.0.5",
    "@reown/appkit-adapter-solana": "^1.0.5",
    "@reown/appkit-adapter-wagmi": "^1.0.5",
    "@solana/wallet-adapter-wallets": "^0.19.32",
    "@tanstack/react-query": "^5.31.0",
    "@web3modal/solana": "^5.1.10",

**Comment by rtomas** [comment]
could you please try in 1.0.7 ?

**Comment by Harushii18** [comment]
It's still an issue with 1.0.7
