### ISSUE TITLE
[feature]  How to support the BLAST network?

### ISSUE THREAD

**Issue by raphaelvserafim** [reown-com/appkit#3004]
### What problem does this new feature solve?

"We don't support the chainId you provided: eip155:81457. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains"
```ts
      BLAST: {
        id: "eip155:81457",
        chainId: 81457,
        chainNamespace: "eip155",
        name: 'Blast Mainnet',
        currency: 'ETH',
        explorerUrl: 'https://blastscan.io',
        rpcUrl: 'https://rpc.blast.io',
        imageUrl: iconeBlast,
        imageId: iconeBlast,
      } as CaipNetwork,
```

```ts
 const e = await contract.methods.balanceOf(_address).call();
```

### Describe the solution you'd like

I'm trying to integrate with a contract on the BLAST network, but I'm not succeeding. Can someone help me?

**Comment by mlenser** [comment]
Thanks for opening this issue as I was under the impression that appkit couldn't handle custom chains until I saw this.

I created a `networks.ts` with the following:

```
import type { CaipNetwork } from '@reown/appkit'

export const berachainTestnetbArtio = {
  chainId: 80084,
  chainNamespace: 'eip155',
  currency: 'BERA',
  explorerUrl: 'https://bartio.beratrail.io',
  id: 'eip155:80084',
  name: 'Berachain bArtio',
  rpcUrl: 'https://bartio.rpc.berachain.com',
} as CaipNetwork

export const networks = [berachainTestnetbArtio]
```

I then used that `berachainTestnetbArtio` on:
- `defaultNetwork` inside `createAppKit`:
```
createAppKit({
  adapters: [wagmiAdapter],
  defaultNetwork: berachainTestnetbArtio,
  metadata,
  networks,
  projectId: ENV.NEXT_PUBLIC_WALLETCONNECT_ID,
})
```
- `wagmiAdapater`
```
export const wagmiAdapter = new WagmiAdapter({
  networks,
  projectId: ENV.NEXT_PUBLIC_WALLETCONNECT_ID,
  ssr: true,
  storage: createStorage({
    storage: cookieStorage,
  }),
})
```

**Comment by hskang9** [comment]
Are we staying with CaipNetwork type? This type is not even compatible to Chain type in Wagmi, and it represents less properties. When is it supporting contracts such as Multicall3 and others?

**Comment by rtomas** [comment]
Please check for latest version and our new docs section -> https://docs.reown.com/appkit/react/core/custom-networks
