### ISSUE TITLE
[docs] NextJS installation docs need some adjustments

### ISSUE THREAD

**Issue by mlenser** [reown-com/appkit#3011]
### Summary

Firstly, thanks for building the appkit.

_Note: I'm more than happy to send a PR for these documentation updates if someone can point me to the repo for the docs._

______

In the first wagmi config section `http` isn't used and can be removed
![image](https://github.com/user-attachments/assets/bd1d7ac3-0b76-4d44-899f-68efa178cc3e)

______

In the ContextProvider section `modal` isn't used. It can be
```
createAppKit({
```
instead of
```
const modal = createAppKit({
```
It's the same in the [react docs](https://docs.reown.com/appkit/react/core/installation)
![image](https://github.com/user-attachments/assets/0ac75cd0-6942-42da-a4fb-f7e38cec0a93)

______

Lastly, I would add a section about supporting custom chains to all of the docs. `viem` supports [a lot of chains](https://github.com/reown-com/blockchain-api/blob/master/SUPPORTED_CHAINS.md). Reown only supports a dozen or so out of the box. I was under the impression that other chains wouldn't work until I saw [[feature] How to support the BLAST network?](https://github.com/reown-com/appkit/issues/3004)

### Link to the related docs page

https://docs.reown.com/appkit/next/core/installation

**Comment by rtomas** [comment]
next.js modal variable fixed here-> https://github.com/reown-com/reown-docs/pull/77/files

custom chain will be soon online ... we are doing some changes in how we are going to use chains.

Thanks
