### ISSUE TITLE
[bug] Multichain Error: Browser Freezes When Wallet Network Differs from AppKit

### ISSUE THREAD

**Issue by mrrohit1** [reown-com/appkit#3018]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/multichain-ethers-solana/

### Summary

When using multichain with MetaMask or Phantom, if the network in the wallet differs from the one selected in AppKit, instead of prompting a network switch, the application throws an error (as shown in the image below, selected network on appkit is ethereum and on wallet its base). Within a few minutes, the browser becomes unresponsive due to the frequency of the error, and I am unable to switch networks or disconnect from the wallet. Even manually disconnecting from the wallet does not stop the error. However, when the wallet and AppKit networks are the same, everything functions correctly.
![Screenshot 2024-10-05 225617](https://github.com/user-attachments/assets/6d650ec6-9634-4f15-b5ea-14fa6dfa0111)

### List of related npm package versions

```
 "@reown/appkit": "^1.0.7",
 "@reown/appkit-adapter-ethers": "^1.0.7",
 "@reown/appkit-adapter-solana": "^1.0.7",
 "@solana/wallet-adapter-wallets": "^0.19.32",
```

**Comment by benjamin890923** [comment]
Hi, I have the same issue. 
I use base as the network, when I join metamask which is linked to ethereum, I have infinite loop of errors.
