### ISSUE TITLE
[docs] Documentation link in Readme is broken

### ISSUE THREAD

**Issue by Harushii18** [reown-com/appkit#3035]
### Summary

The link shows a 404 not found when clicking on it.

### Link to the related docs page

https://docs.reown.com/appkit/about

**Comment by rtomas** [comment]
Hi ! 
Where do you click to go to that web ?

**Comment by Harushii18** [comment]
The documentation link in Readme(first link with the books emoji)

**Comment by rtomas** [comment]
can't find it .. can you please send a screen capture ?

**Comment by Harushii18** [comment]
Hi it is in the Readme, the first section, you can ctrl+f for Documentation. I cannot send screenshots due to organization policies.



Internal - Intellectual Property
