### ISSUE TITLE
[bug] `useAppKitProvider` not exporting `connection` as documented in reown documentation

### ISSUE THREAD

**Issue by DaveTheFrontEndDev** [reown-com/appkit#3042]
### Link to minimal reproducible example

https://github.com/DaveTheFrontEndDev/reown-solana-transaction-bug

### Scenario
Using the React reown libraries in a simple vite setup, implementing the `wagmi+solana` multichain setup 

Documented in the example [here](https://docs.reown.com/appkit/react/core/multichain)

### Expected Behavior
`useAppKitProvider` hook should return a connection value as documented [here (smart contract interaction section)](https://docs.reown.com/appkit/react/core/installation?platform=solana)

### What is Actually Happening
`connection` is not being exported in the `useAppKitProvider` hook.

### Producing the Bug
Simple Vite React app example
**Bug 2 in repo**

1) Copy `.env.example` into new file `.env` and replace with project id from [here](https://cloud.walletconnect.com/sign-in)

2) Run code example:
```
yarn install && yarn dev
```

### Example Preview

https://github.com/user-attachments/assets/bf641969-34f4-43e4-b39f-2e9f08f2f3b6

### List of related npm package versions

@reown/appkit: ^1.0.6
@reown/appkit-adapter-solana: ^1.0.7
@reown/appkit-adapter-wagmi: ^1.0.6
@reown/appkit-solana: ^1.0.6
@solana/wallet-adapter-wallets: ^0.19.32
@solana/web3.js: ^1.95.3
@tanstack/react-query: ^5.59.2
viem: ^2.21.15
react: ^18.2.0
wagmi: ^2.12.16

**Comment by rtomas** [comment]
please use useAppKitProvider('eip155') or useAppKitProvider('solana');
