### ISSUE TITLE
[feature] SIWS support

### ISSUE THREAD

**Issue by kharlanchuk47** [reown-com/appkit#3044]
### What problem does this new feature solve?

Now AppKit has AppKitSIWEClient which allows me to easily configure SIWE authorization for EVM networks.

Are there any plans to do the same for Solana (SIWS)?

### Describe the solution you'd like

Add the siwsConfig parameter to the createAppKit function, similar to SIWE.

**Comment by rtomas** [comment]
We are working on it. 
I Hope to have new soon.

**Comment by arein** [comment]
@zoruka is just shipping this - @kharlanchuk47 can you dm me on Telegram so we can onboard you? `cyberdrk`
