### ISSUE TITLE
[bug] Coinbase wallet not available when networks = [ base ] unless it's a featured wallet id

### ISSUE THREAD

**Issue by evvvritt** [reown-com/appkit#3047]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/l8vgjp

### Summary

Oddly, Coinbase Wallet is not available in "All Wallets" when `networks = [base]`, only when `mainnet` is present.
[demo](https://codesandbox.io/p/devbox/l8vgjp)

If you include Coinbase Wallet in the `featuredWalletIds` it is always available. (uncomment the ID in the demo to observe this)

### List of related npm package versions

```
"@reown/appkit": "^1.1.0",
"@reown/appkit-adapter-wagmi": "^1.1.0",
"@tanstack/react-query": "^5.59.3",
"react": "^18.3.1",
"viem": "^2.21.19",
"vue": "^3.4.15",
"wagmi": "^2.12.17"
```

**Comment by rtomas** [comment]
internal: https://linear.app/reown/issue/APKT-1739/%5Bbug%5D-coinbase-not-appearing-when-using-base-blockchain
