### ISSUE TITLE
[bug] Error: failed to get balance of account

### ISSUE THREAD

**Issue by bonnusi** [reown-com/appkit#3050]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/solana/

### Summary

The error drops with some unclear frequency 
`Uncaught (in promise) Error: failed to get balance of account [account]: n: Expected the value to satisfy a union of 'type | type', but received: [object Object]`

This problem not only for Phantom wallet, also for trust wallet and solflare wallet

Network - solana mainnet

https://github.com/user-attachments/assets/d341b12c-cb2c-40c2-8123-f1045d0fbdd2

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/65618e4b-b892-4d34-9d4a-6d31c6a1de43">
<img width="641" alt="image" src="https://github.com/user-attachments/assets/9cd2bf52-50ca-4d06-80a2-28f38b5df76d">
<img width="590" alt="image" src="https://github.com/user-attachments/assets/ebe81710-0016-4528-91ff-fe596692f6b0">

### List of related npm package versions

 "@reown/appkit": "1.0.7",
    "@reown/appkit-adapter-solana": "1.0.7",
    "@tanstack/react-query": "5.24.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "vite": "5.2.11",
    "@solana/wallet-adapter-backpack": "0.1.14",
    "@solana/wallet-adapter-wallets": "0.19.32"

**Comment by DaveTheFrontEndDev** [comment]
Also encountered this issue, and experienced this intermittently. I have a code example with it set up here https://github.com/DaveTheFrontEndDev/reown-solana-transaction-bug although my last local test works fine
