### ISSUE TITLE
Add missing chains

### ISSUE THREAD

**Issue by Madeindreams** [reown-com/appkit#3054]
### What problem does this new feature solve?

There are new testnets and layer2 available.

eg;
Polygon Amoy
Scroll
Scroll Speolia
and others that are not available in the app kit.

Even if i just create it, i am not allowed to switch network.

![image](https://github.com/user-attachments/assets/26f87db8-1a31-41c9-a18d-16efdddb6a7d)

### Describe the solution you'd like

I would like the list of chains to be up to date or be able to add them

**Comment by rtomas** [comment]
Pleaes check our new section in our docs -> https://docs.reown.com/appkit/react/core/custom-networks
