### ISSUE TITLE
[bug] useAppKitProvider() returns walletProvider as undefined

### ISSUE THREAD

**Issue by AnesBkdm** [reown-com/appkit#3071]
### Link to minimal reproducible example

https://github.com/AnesBkdm/walletprovider-issue

### Summary

Rebounding on this issue posted by @DaveTheFrontEndDev:

https://github.com/reown-com/appkit/issues/3043

We are using the latest Nextjs packages and AppKit on Etherers v5. useAppKitProvider() returns "undefined", which makes actions like signing a message (login) impossible. Please advise.

<img width="1726" alt="Screenshot 2024-10-11 at 11 01 57" src="https://github.com/user-attachments/assets/bc90648a-1764-44c0-86cf-34ae901a7f6b">

### List of related npm package versions

```js
"dependencies": {
    "@reown/appkit": "^1.1.2",
    "@reown/appkit-adapter-ethers": "^1.1.2",
    "ethers": "^6.13.3",
    "next": "14.1.0",
    "react": "^18",
    "react-dom": "^18"
  },
```

**Comment by zugdev** [comment]
Bump, also docs are outdated.

**Comment by rtomas** [comment]
Updating right now the docs. 

```
import { useAppKitAccount, useAppKitProvider,useAppKitNetwork  } from '@reown/appkit/react'
import { ethers, JsonRpcSigner } from 'ethers'

const compactHash = (hash: string) => {
  return hash.slice(0, 7) + '...' + hash.slice(-5)
}

export const ConnectButton = () => {
  const { address } = useAppKitAccount()
  const { chainId } = useAppKitNetwork()
  const { walletProvider, walletProviderType } = useAppKitProvider('eip155')

  async function onSignMessage() {
      if (!walletProvider || !address) {
        throw Error('user is disconnected')
      }
      console.log('Signing message...')

      const provider = new ethers.providers.Web3Provider(walletProvider, chainId)
      const signer = provider.getSigner(address)
      const sig = await signer?.signMessage('Hello AppKit!')
      console.log('Signature:', sig)
  }

  return (
    <div className="column">
      <button onClick={onSignMessage}>Sign Message</button>
      <w3m-button />
    </div>
  )
}
```

**Comment by rtomas** [comment]
PR -> https://github.com/reown-com/reown-docs/pull/97

**Comment by zugdev** [comment]
Thanks bro, that's great

**Comment by zugdev** [comment]
@rtomas pinging because it's related, https://docs.reown.com/advanced/providers/ethereum is very poor in explaining how to use universal providers. The section that should explain how to use it with appkit is empty in content:

![image](https://github.com/user-attachments/assets/18e2813e-5ade-44dd-bf10-25193ea4984d)

I think it should be at least a team goal to have easy default providers made accessible.
