### ISSUE TITLE
[bug] Multichain: WagmiAdapter + SolanaAdapter not working

### ISSUE THREAD

**Issue by Alangr6** [reown-com/appkit#3078]
### Link to minimal reproducible example

  createAppKit({     adapters: [wagmiAdapter, solanaWeb3JsAdapter],     networks: [       mainnet,   sepolia,       solana,       solanaTestnet,       solanaDevnet], projectId,     metadata})

### Summary

If I only add one of the adapters (either the WagmiAdapter or the SolanaAdapter) to the createAppKit, everything works fine. However, when both are added and I connect a Solana wallet—Phantom, in this case—the session in localStorage (specifically the @appkit/wallet_id parameter) gets automatically removed upon refreshing the page. Ethereum wallets continue to work fine, and if only the SolanaAdapter is added, this bug does not occur either. The issue arises when both adapters are configured; in this case, the @appkit/wallet_id in localStorage gets removed for Solana wallets.

### List of related npm package versions

import { createAppKit } from '@reown/appkit/react';

**Comment by ozgurrgul** [comment]
Bump the versions as following and should work:

``` json
"@reown/appkit": "1.2.0",
"@reown/appkit-adapter-solana": "1.2.0",
"@reown/appkit-adapter-wagmi": "1.2.0",
"@solana/wallet-adapter-wallets": "^0.19.32",
```

**Comment by arein** [comment]
We've fixed this meanwhile - sorry about the radio silence - curious - what are you building? :)

**Comment by Alangr6** [comment]
Hello, I have another question.

I want to only add the wallet connect feature without the rest of the
browser extension wallets. Can I integrate wallet connect without all the
other libraries like wagmi, adapters, etc?

I'm only looking for the wallet connect feature.

Thanks
