### ISSUE TITLE
[bug] Error while verifying multi-line SIWE message

### ISSUE THREAD

**Issue by thomasvalera** [reown-com/appkit#3092]
### Link to minimal reproducible example

https://github.com/thomasvalera/AppKit-Multiline-Siwe

### Summary

Hey! I've been scratching my head for too long today on this issue and would love some input on it :)

So I'm trying to create a multiline SIWE message and while it works fine in the front end, verifying it on the server throws an error.

For this I've been using the AppKit-Siwe React project and attached an mre with a multiline message as only change.

Anyway, here's how the message is created:

```
src/utils/siweUtils

const MESSAGE = 'Welcome to the dApp!\nPlease sign this message';

{...}

export const createSIWE = (chains: [AppKitNetwork, ...AppKitNetwork[]]) => {
    return createSIWEConfig({
        {...}
        getMessageParams: async () => ({
              domain: window.location.host,
              uri: window.location.origin, 
              chains: chains.map((chain: AppKitNetwork) => parseInt(chain.id.toString())),
              statement: MESSAGE,
            }),
        {...}
    })
}
```

It works fine without the "\n" but fails otherwise. I've also tried other ways to write multilines but without success like this:

```
const MESSAGE = 'Welcome to the dApp!
Please sign this message';
```

Signing it on the front end works fine but it's on the server side that it fails, here to be precise:

```
server/server.js

app.post('/verify', async (req, res) => {
     {...}

      // This line throws an error
      let SIWEObject = new SiweMessage(req.body.message);
      
      {...}  
```

And this is the error:

`
Error: Invalid message: {"success":false,"state":103,"length":270,"matched":0,"maxMatched":132,"maxTreeDepth":15,"nodeHits":1309,"inputLength":270,"subBegin":0,"subEnd":270,"subLength":270}
`

What's weird is that it works fine with single lines AND it works fine if I manually create the message with parameters like this :

```
const params = {
        domain: "localhost:3000",
        address: "0x6b2Ed7E4b12A544ca7D215fED85dC16240D64aee",
        statement: `Welcome to the dApp!\nPlease sign this message`,
        uri: "http://localhost:3000",
        version: "1",
        chainId: 1,
        nonce: "aaabbb",
      };

      // This works fine and doesn't throw an error!!
      let SIWEObject1 = new SiweMessage(params);
```

Also, platforms like opensea managed to have multiline messages too, although I don't know if they use AppKit for that ;)      

If you've got some ideas I'm all ears! 

Thanks!

### List of related npm package versions

"@tanstack/react-query": "^5.53.1",
    "@wagmi/core": "^2.13.4",
		"@reown/appkit-siwe": "^1.1.2",
    "@reown/appkit": "^1.1.2",
    "@reown/appkit-adapter-wagmi": "^1.1.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "viem": "^2.21.0",
    "wagmi": "^2.12.7"

**Comment by rtomas** [comment]
it's working ok on next.js -> https://github.com/reown-com/web-examples/tree/main/dapps/appkit-siwe/next

I'll try to investigate more ...

**Comment by rtomas** [comment]
I just fixed the React SIWE example.
https://github.com/reown-com/web-examples/tree/feat/create-appkit-examples/dapps/appkit-siwe/react

Please check the changes over the server
