### ISSUE TITLE
[bug] Login State Sync Delay Between useAccount and useAppKitAccount After Page Refresh

### ISSUE THREAD

**Issue by tsuki2478** [reown-com/appkit#3114]
### Link to minimal reproducible example

https://github.com/tsuki2478/test-appkit

### Summary

When the user is logged in and refreshes the page, wagmi's useAccount hook immediately recognizes the isConnected state, but useAppKitAccount from @reown/appkit takes a few seconds to reflect the same state. This causes a delay in displaying the login-dependent data, affecting user experience. 

 Is there a way to synchronize the login state faster between wagmi and appkit? Any suggestions or configurations to ensure both states are in sync right after the page refresh?

https://github.com/user-attachments/assets/a538fcb3-b457-48ff-8dbd-ac5762e05193

### List of related npm package versions

"@reown/appkit": "^1.1.5"
"@reown/appkit-adapter-wagmi": "^1.1.5"
viem: ^2.21.27
wagmi: ^2.12.18

**Comment by FrankD6EAF** [comment]
```ts
AccountController.subscribe((status) => {
    console.log(status.address);
})
```

**Comment by arein** [comment]
@tsuki2478  @FrankD6EAF we've fixed this - apologies about the radio silence - can you please upgrade to v1.6.0?

Also curious what are you building? Would love to see!
