### ISSUE TITLE
[bug] Switching addresses doesn't work on AppKit + Ethers

### ISSUE THREAD

**Issue by jakub-musik** [reown-com/appkit#3118]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/ethers/

### Summary

Account switching doesn't work when using AppKit with erhers. This can be seen in the linked appkit-lab example: 

- connect with metamask
- within metamask connect another address
- in the appkit modal now your address is clickable and you can try to switch between them
- clicking "switch to" does not switch the address, just closes the modal
- switching addressess in metamask breaks the modal, requiring a refresh
![image](https://github.com/user-attachments/assets/9e839367-2bec-46ba-b0f2-b7b6d547e115)

### List of related npm package versions

all @reown/appkit packages on 1.1.5, ethers 6.13.4,

**Comment by arein** [comment]
We've fixed this meanwhile - @jakub-musik sorry about this - what are you building?
please upgrade to v1.6.0 or later
