### ISSUE TITLE
[bug][docs] Vue Docs are not good enough & Vue Support in General is Lacking Severely

### ISSUE THREAD

**Issue by ZachHandley** [reown-com/appkit#3122]
### Summary

There's not really a better way to describe it other than nobody is using the Vue docs or?

It sticks with React in a lot of the installation steps

The `getAccount` is incorrect, as is the `useDisconnect`, which literally references a `react` function in the composables section (see screenshot) 
![image](https://github.com/user-attachments/assets/dc4ec7c4-23bd-466c-9c03-bdcc9d96703d)

'Compostable'
![image](https://github.com/user-attachments/assets/f491ed95-28a6-4902-a777-f047116f4098)

I mean hell, this is in the Dashboard for gods sake

![image](https://github.com/user-attachments/assets/b9094878-0cc8-45a4-9cdd-47de444dda47)

I can't open Swap Menu

![image](https://github.com/user-attachments/assets/bad6dbcd-4072-4b90-b6ef-20c37109d8e9)

I know there's more, I just am not going to go through the docs entirely and bash my head against the wall trying to find them

I get that you guys did some big fancy rebrand, but I am trying to migrate and it's as if you didn't even check the docs or try to use them (not from a developer of Reown's perspective) -- cause these are crap and missing so many answers.

### Link to the related docs page

https://docs.reown.com/appkit/vue/core/composables

**Comment by ZachHandley** [comment]
It's kinda sad I even have to do this, but bump.

This is an entire framework you are just... ignoring?

**Comment by obumnwabude** [comment]
I confirm that Vue doesn't work out of the box. You keep seeing console errors like:

> SignInButton.vue:27 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

But this is Vue and I wander what React and hooks is doing in the errors. 

Even worse, you see other errors like:

> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'useContext')
    at useContext (chunk-5DQ77UTZ.js?v=eadcb66c:1347:29)
    at useConfig (wagmi.js?v=eadcb66c:1492:68)
    at useDisconnect (wagmi.js?v=eadcb66c:4267:18)
    at setup (SignInButton.vue:27:39)
    
useContext is React stuff just you @ZachHandley is saying. I was expecting Pinia stores or something is similar. Please what's the way forward?

**Comment by rtomas** [comment]
hi ! 
- useDisconnect is available since v1.1.7
- Quickstart for vue is wrong in cloud ... we will fix it .. thanks for reporting it. 
- "I can't open Swap Menu" .. can you give us more context (packages/version) and some code snippets.

This is a place to help each other and try to improve together. I'm here to assist you and enhance our communication. :)

**Comment by rtomas** [comment]
hi @obumnwabude 

Can you please share with me what would you like to improve in our docs ?

**Comment by ZachHandley** [comment]
@rtomas Please man, this is like, so tone deaf.

> I know there's more, I just am not going to go through the docs entirely and bash my head against the wall trying to find them

I get that you'd like me to provide you with all instances where the Vue docs are busted, but like. Try setting up a project with Vue. Open up each of the modals. Just like, give things a try and see if you can successfully open every single modal, triggered, and setup the configuration options, and you'll _**see**_ where all of the `yeah just add tanstack-react` type deal stuff is, and it's so evident that nobody is using Vue on the dev team. I'm happy to hop in a call with you guys and go over it or something, but like all I did was uninstall walletconnect and wagmi/viem and what not, and then install the recommended packages into the project, and try to use it.

**Comment by rtomas** [comment]
Thanks for reporting the issue. We will be working on vue docs ASAP.

Also our repository is open and you can contribute.This would be greatly appreciated.

I can transfer the Issue, so I'm closing it. You can reopen in the Docs Repository.

**Comment by obumnwabude** [comment]
Hi @rtomas 

After I wrote in this issue above, I kept searching and landed on [this solution](https://github.com/reown-com/appkit/issues/2874#issuecomment-2405147658). Installing @wagmi/vue and @tanstack/vue-query as the solution suggested, and configuring Vue Plugin integration both helped. But with help of my programming expertise, I figured out how to manoeuvre imports and to get it things to work.

You've closed this issue and as you rightly said, doc-related problems should be mentioned in the docs repo. But please here are my two cents.

As for what I want updated in the docs, add the @wagmi/vue and @tanstack/vue-query packages to the list of packages during installation in Vue. Also, update the code examples, ensure they work, and provide more. 

Cheers.

**Comment by ZachHandley** [comment]
![image](https://github.com/user-attachments/assets/04441dfa-63ba-41e8-8c10-7bafddf9da06)

so like, things like this for instance, still broken. I think it's laughable a company would close this ticket, you're providing a service and doing it pathetically.

**Comment by enesozturk** [comment]
Hey @ZachHandley, following the conversation here. You're right that the docs might be a bit out of date or not really helpful at some points. Recently we've updated all our Vue examples in the repo: https://github.com/reown-com/appkit/pull/3157, you can see our example setups for each adapter here: https://github.com/reown-com/appkit/tree/main/examples. 

Please let me know if you still encounter any setup issues.

> things like this for instance, still broken

Could you be more specific about the issues please? The issue I'm seeing in the pic is that your value for `view` property is not one of the options we've provided so far. For which use cases you want to trigger other views manually? We could make the other screens enable to call.

**Comment by ZachHandley** [comment]
@enesozturk a few things

1. The Vue example is the bare minimum for something to work, I am trying to read the blockchain using wagmi/tanstack alongside it, or other things that I am currently unable to do

2.  > Please let me know if you still encounter any setup issues.

When I show the type support missing, it's because those things do, in fact, exist. The screens I'm referring to aren't typed correctly, so the screens are busted.

When I say setup issues I mean the fact that I can rarely get `wagmi` and `vue-tanstack` to accept the WAGMI Config you guys use because the types are rarely in sync

![image](https://github.com/user-attachments/assets/0acb3870-ef86-426d-8f14-baa023680d02)

```ts
import { createAppKit, useAppKit } from "@reown/appkit/vue";

import { WagmiProvider } from "wagmi";
import { mainnet, sepolia } from "viem/chains";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";

import { WALLETCONNECT_ID } from "astro:env/client";
// import { createConfig } from "@wagmi/vue";
// import { http } from "viem";
// import { walletConnect, coinbaseWallet, injected } from "@wagmi/connectors";
// import { authConnector } from "@web3modal/wagmi";

const projectId = WALLETCONNECT_ID;
const metadata = {
  name: "ProjectName",
  description:
    "Our project name",
  url: import.meta.env.SITE,
  icons: ["ourlogo.svg"],
};

const networks = [mainnet, sepolia];

const wagmiAdapter = new WagmiAdapter({
  ssr: true,
  projectId,
  networks,
});

const modal = createAppKit({
  projectId: projectId,
  adapters: [wagmiAdapter],
  networks: [mainnet, sepolia],
  metadata: metadata,
  features: {
    swaps: true,
    onramp: true,
    email: true,
    socials: [
      "google",
      "x",
      "discord",
      "farcaster",
      "github",
      "apple",
      "facebook",
    ],
    history: true,
    analytics: true,
    allWallets: true,
  },
});

const appKit = useAppKit();
const wagmiConfig = wagmiAdapter.wagmiConfig;

export { wagmiAdapter, modal, appKit, wagmiConfig };
```

and then inside my ConnectWallet it doesn't even open -- you guys removed the watchAccount and other things, so I am using the AppKit to subscribe to changes

I can't open Swap view either. It does try, but it gives an error about react.
