### ISSUE TITLE
[bug] Modal shrinks when select wallet to connect

### ISSUE THREAD

**Issue by Philword** [reown-com/appkit#3125]
### Link to minimal reproducible example

https://test.astroarmadillos.io/

### Summary

When open modal I have option to select wallet to connect to. When I click on wallet it shrinks and I'm not able to connect. 
I was able to connect only when activated email connect (`emailShowWallets: true,` and `email: true`) and after input email and then canceled connecting, click on metamask wallet it started working. 
How to solve it? 
Url with website were I have this issue provided.
https://test.astroarmadillos.io/

![IMG_3298](https://github.com/user-attachments/assets/c395a0c9-b059-4435-9c10-1e5b8d87adcc)

### List of related npm package versions

import { createAppKit } from '@reown/appkit/vue'
import { EthersAdapter } from '@reown/appkit-adapter-ethers'
import { mainnet, polygon } from '@reown/appkit/networks'
import { useAppKitProvider, useAppKitAccount } from "@reown/appkit/vue"
import { BrowserProvider } from 'ethers'

const modal = createAppKit({
  adapters: [new EthersAdapter()],
  networks: [polygon],
  metadata,
  projectId,
  themeMode: 'light',
  features: {
    analytics: false,
    email: false, // default to true
    socials: false,
    emailShowWallets: false,
    swaps: false,
  }
})

modal.switchNetwork(polygon)

**Comment by Philword** [comment]
If anyone ever face with the same issue on NUXT3 here is the solution:

put this after initiate `createAppKit`:

```
if (process.client) {
  localStorage.setItem('@appkit/connected_connector', 'WALLET_CONNECT');
}
```

**Comment by arein** [comment]
@Philword thank you so much - do you still need this workaround in v1.6.0?

Sorry about this and the radio silence here - won't happen again!
