### ISSUE TITLE
[bug] Issue in switchNetwork ethers

### ISSUE THREAD

**Issue by chirag9899** [reown-com/appkit#3126]
### Link to minimal reproducible example

https://github.com/chirag9899/walletConnect_Issue

### Summary

there are two function get balance tokens getwbera and getusdc both get balance on diffrent chain 
in these function i have switched chain using web3wallet.switchNetwork(chain) shows networkswitched chainid also changed correctly but when query blockchain 
`call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)`
but when am using modal open({view: "Network"}) to switch chain balance successfully queried .

### List of related npm package versions

 "@reown/appkit": "^1.1.6",
 "@reown/appkit-adapter-ethers5": "^1.1.6",

**Comment by arein** [comment]
@chirag9899 apologies - pretty sure this is fixed now - can you try 1.6.0? Also what are you building? Excited to see!

**Comment by chirag0264** [comment]
lol I was working with snapshot , back then. Have to switched to custom solution. But thanks for asking🙌
