### ISSUE TITLE
[docs] there is no method of modal.disconnect()

### ISSUE THREAD

**Issue by zhanzhanxi** [reown-com/appkit#3138]
### Summary

https://docs.reown.com/appkit/javascript/core/actions
The document provides this method, but when I use it, it prompts that there is no such method. Is there any other way to close the wallet connection?

### Link to the related docs page

https://docs.reown.com/appkit/javascript/core/actions

**Comment by klugjo** [comment]
Same here

**Comment by rtomas** [comment]
duplicated 
https://github.com/reown-com/appkit/issues/2885

Please use for the moment: modal.adapter?.connectionControllerClient?.disconnect()

**Comment by zhanzhanxi** [comment]
Forgive me for not noticing that there is already this issue, modal.adapter.connectionControllerClient.disconnect() works，Thank you so much。 but i got annother problem , i can use modal.subscribeCaipNetworkChange() to subscribe Chain Change Events, how could i subscribe account change events ? Looking forward to your professional answer

**Comment by zhanzhanxi** [comment]
modal.subscribeShouldUpdateToAddress() does not works

**Comment by zhanzhanxi** [comment]
AccountController.subscribe() works , this method can be used to monitor account switching change events
