### ISSUE TITLE
[bug] Unable to add network and other issues in appkit@1.1.7 migration

### ISSUE THREAD

**Issue by ms-safiq** [reown-com/appkit#3145]
### Link to minimal reproducible example

Code snippet added in Summary

### Summary

Hi Team,

I have recently upgraded from web3Modal/ethers@5.1.7 to reown/appkit@1.1.7. During our testing, we were facing the below issues.

Here is my config
`let wcMetadata = {
      name: "***",
      description: environment.selfDomain,
      url: environment.selfDomain,
      icons: [environment.selfDomain + "/assets/icons/logo.svg"],
    };`

    `this.wcModal = createAppKit({
      adapters: [new EthersAdapter()],
      networks: [arbitrumSepolia],
      allowUnsupportedChain: false,
      metadata,
      "****", // projectID
      debug: true,
      themeMode: "dark",
      defaultNetwork: arbitrumSepolia,
      termsConditionsUrl: "https://docs.defx.com/docs/terms-and-conditions",
      features: {
        socials: ["google", "x", "apple"],
        analytics: true,
        onramp: true,
        email: true,
      },
    });`
    
Issue 1:

With this configuration, its not listing any wallets in my PWA when i open the modal. I can able to see all wallets only when i mention mainnet/goerli in the networks field. But I cannot mention these networks as we are supporting only arbitrum. This is working fine in web3modal/ethers. Now in the appkit, I am not able see metamask, trust wallet or any other wallets. Snapshot below. 

![WhatsApp Image 2024-10-24 at 6 18 03 PM](https://github.com/user-attachments/assets/5ddb4e9a-437d-4049-833e-9eb083fdbfd9)

Issue2:

We are unable to request wallet_addEthereumChain to the Metamask mobile or any other mobile wallet. Below is the code we are using to add the network (For ex, arbitrumSepolia).

`promptToAddNetwork() {
    return new Promise<void>((resolve, reject) => {
      this.showAddNetwork.next(true);
      this.provider
        .send("wallet_addEthereumChain", [
          {
            chainId: environment.hexChainId,
            rpcUrls: [environment.rpcUrl],
            chainName: environment.chainName,
            nativeCurrency: {
              name: environment.symbol,
              symbol: environment.currency,
              decimals: environment.decimals,
            },
            blockExplorerUrls: [environment.explorerUrl],
          },
        ])
        .then(
          () => {
            
          },
          (error: any) => {
            reject(error);
          },
        );
    });
  }
`

And we are getting the below error. It says the method is available or doesnt exist. This was working fine in web3modal/ethers

`unsupported operation (operation="wallet_addEthereumChain", info={ "error": { "code": -32601, "message": "the method wallet_addEthereumChain does not exist/is not available" }, "payload": { "id": 2, "jsonrpc": "2.0", "method": "wallet_addEthereumChain", "params": [ { "blockExplorerUrls": [ "https://sepolia.arbiscan.io" ], "chainId": "0x66eee", "chainName": "Arbitrum Sepolia", "nativeCurrency": { "decimals": 18, "name": "Ethereum", "symbol": "ETH" }, "rpcUrls": [ "https://sepolia-rollup.arbitrum.io/rpc" ] } ] } }, code=UNSUPPORTED_OPERATION, version=6.13.4)
    at makeError (errors.js:124:21)
    at BrowserProvider.getRpcError (provider-jsonrpc.js:722:29)
    at BrowserProvider.getRpcError (provider-browser.js:67:22)
    at provider-jsonrpc.js:298:45
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:14723:33)
    at _ZoneDelegate.invoke (zone.js:367:52)`

Issue 3:

Why the subscribeProvider() is returning null. I can see only subscribeProvider(): null; in the package. 
When I refresh the page, the wallet connect session is not restoring automatically even though I have connected to the wallet. I need to call getWalletPrvoider() on MODAL_LOADED event to make it connected and then it starts sending the states callback.

Issue 4:

We can able to see Meld as an onramp provider. Even when we mention the network as arbitrum, the meld is launching with Etherum as a network. Since we are supporting only arbitrum, how can we change the network from Etherum to arbitrum. Snapshot below:

<img width="496" alt="373513394-2f1717bb-d458-4654-8cb2-fdcd401e17e1" src="https://github.com/user-attachments/assets/b421fe70-1056-413c-850e-411b81151674">

Please guide/address us on these issues, so that we can upgrade to reown/appkit. 

### List of related npm package versions

"@reown/appkit": "^1.1.7",
"@reown/appkit-adapter-ethers": "^1.1.7",

**Comment by rtomas** [comment]
i1: working on it
i2: can you use switchNetwork from -> https://docs.reown.com/appkit/react/core/hooks#useappkitnetwork  or check the custom networks docs -> https://docs.reown.com/appkit/react/core/custom-networks?
i3: do you have a minimal reproducible example ?
i4: working on it

Is very difficult to follow all the issues in one thread.

**Comment by ms-safiq** [comment]
@rtomas can we remove meld option from onramp?

**Comment by arein** [comment]
@ms-safiq can you please upgrade to the latest version? Most issues I believe have been fixed - also what are you building? :)
