### ISSUE TITLE
Issue with Address Undefined When Switching Accounts in MetaMask Using "@reown/appkit-adapter-ethers

### ISSUE THREAD

**Issue by im-shubh** [reown-com/appkit#3151]
### Link to minimal reproducible example

const { address, isConnected, caipAddress } = useAppKitAccount();
const { open } = useAppKit();

<Button
  style={{
    borderRadius: '10px',
    background: themeGlobal.palette.button.background,
    marginLeft: 'auto',
    color: '#fff',
    width: '159px',
    height: '40px',
    flexShrink: '0',
  }}
  onClick={() => open()}>
  {formatAddress(address)}
</Button>

### Summary

I'm using "@reown/appkit-adapter-ethers": "^1.1.4" and I'm connected to MetaMask with account 1. When I switch from account 1 to account 2 in MetaMask and connect with account 2, I get undefined for the address:

const { address, isConnected, caipAddress } = useAppKitAccount();

While I do get account 2's address in caipAddress, the address being undefined is causing issues with disconnecting and other functionalities since the app relies on the address field.

Here’s the button code:

const { open } = useAppKit();

<Button
  style={{
    borderRadius: '10px',
    background: themeGlobal.palette.button.background,
    marginLeft: 'auto',
    color: '#fff',
    width: '159px',
    height: '40px',
    flexShrink: '0',
  }}
  onClick={() => open()}>
  {formatAddress(address)}
</Button>

Because the address is undefined, the UI breaks when handling disconnect and other actions.

Could you please guide me on how to resolve this or suggest an alternative approach to handle the address field properly in AppKit?

### List of related npm package versions

@reown/appkit-adapter-ethers : "^1.1.4,
ethers :6.13.2,

**Comment by rtomas** [comment]
It's working ok in 1.2.1
