### ISSUE TITLE
[bug] The MetaMask wallet does not appear on mobile devices when using a custom network.

### ISSUE THREAD

**Issue by tom2drum** [reown-com/appkit#3178]
### Link to minimal reproducible example

https://tcthc3-5173.csb.app/

### Summary

I am migrating from `@web3modal` to `@reown` packages and have noticed a difference in behavior. When I specify a custom network in the config (e.g., `optimism`) and open the modal on a mobile device (I use an iPhone with the Chrome browser), the list of available wallets does not include the MetaMask wallet. However, if I use the default network (`mainnet`), it appears. Overall, the "All wallets" list is much shorter for custom networks compared to the default one.

<details><summary>Screenshots</summary>

![IMG_1732](https://github.com/user-attachments/assets/c8ac045d-9ab6-4644-8bac-ce08c2904c49)
![IMG_1733](https://github.com/user-attachments/assets/94a22a81-e582-41c5-99c4-b40cbc0a7e79)

</details> 

[Codesandbox link](https://codesandbox.io/p/devbox/tcthc3)
[Preview link](https://tcthc3-5173.csb.app/)

### List of related npm package versions

```
"dependencies": {
  "@reown/appkit-adapter-wagmi": "1.2.0",
  "@reown/appkit-common": "1.2.0",
  "@reown/appkit": "1.2.0",
  "@tanstack/react-query": "5.59.16",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "viem": "2.21.37",
  "wagmi": "2.12.25"
}
```

**Comment by betranthanh** [comment]
You can use the featuredWalletIds option to add the id of the Metamask Wallet like this: featuredWalletIds: ['c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96']
Document: https://docs.reown.com/appkit/react/core/options

**Comment by arein** [comment]
@tom2drum @betranthanh apologies - we've fixed this meanwhile - sorry for the radio silence

what apps are you building? Can we see?
