### ISSUE TITLE
[bug] Solana `WalletConnectProvider` not emitting `accountsChanged` events

### ISSUE THREAD

**Issue by gcangussu** [reown-com/appkit#3183]
### Link to minimal reproducible example

https://github.com/gcangussu/wallet-connect-provider-missing-events?tab=readme-ov-file#accountschanged-bug-repro

### Expected behavior

From a wallet connected with WalletConnect, we can change the current selected Solana account on a dapp.

Technically, when receiving a ["WalletConnect" `accountsChanged` event](https://specs.walletconnect.com/2.0/specs/clients/sign/session-events#session_event), the Solana's [`WalletConnectProvider`](https://github.com/reown-com/appkit/blob/2af6ac0dbd6bb2a216c02ea004e39979e652760d/packages/adapters/solana/src/providers/WalletConnectProvider.ts#L26) must emit a "Solana" `accountsChanged` event (defined by its [provider interface](https://github.com/reown-com/appkit/blob/2af6ac0dbd6bb2a216c02ea004e39979e652760d/packages/appkit-utils/src/solana/SolanaTypesUtil.ts#L81)) with the first account from the original event as the payload. The difference from the events is that the "WalletConnect" `accountsChanged` event has an array of strings representing account addresses, and the "Solana" `accountsChanged` event is just a single `PublicKey` representing a single account that should be the current selected account.

Here is where the [Solana's chain adapter handles it](https://github.com/reown-com/appkit/blob/2af6ac0dbd6bb2a216c02ea004e39979e652760d/packages/adapters/solana/src/client.ts#L592-L594), expecting an `accountsChanged` with a single `PublicKey` as parameter.

For an example of this being done correctly by a provider in another context see the [implementation on Solana's `WalletStandardProvider`](https://github.com/reown-com/appkit/blob/2af6ac0dbd6bb2a216c02ea004e39979e652760d/packages/adapters/solana/src/providers/WalletStandardProvider.ts#L262-L270).

### Actual behavior

There is no `accountsChanged` event being emitted by the Solana's `WalletConnectProvider`. Consequently, we cannot change the current selected Solana account from the wallet when connected to a dapp by WalletConnect.

Notice that this works fine when 
1. using Solana with "WalletStandard" (e.g. Phantom wallet connection)
2. or when using Ethereum blockchains/accounts with WalletConnect.

The problem is just with the Solana adapter with the underlying WalletConnect provider. So (1) shows that the Solana chain adapter is handling the accountsChanged event correctly (i.e. the problem is in the provider probably), and (2) that other chains adapters and WalletConnect providers are handling it correctly.

### Affected

- Chains: Solana blockchains (mainnet, testnet, and devnet)
- Platforms: all relying on package @reown/appkit-adapter-solana (e.g. AppKit) when using WalletConnect for the connection with the wallet

### List of related npm package versions

@reown/appkit-adapter-solana <= 1.2.0 (as of written)

**Comment by zwq652997** [comment]
I also encountered this problem, when can it be solved?

When the user switches wallets, the monitoring is not available

**Comment by arein** [comment]
@gcangussu @zwq652997 - apologies for the radio silence - let me check and get back
