### ISSUE TITLE
[bug] switchNetwork exposes project ID and stores it in user wallet (impersonating project)

### ISSUE THREAD

**Issue by vittominacori** [reown-com/appkit#3187]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi/

### Summary

If a user wants to switch to a network that has not been added to their network list, the `switchNetwork` hook (or `modal.switchNetwork`) suggests the walletconnect rpc instead of the default rpcurl, exposing the project ID and storing it in the user's wallet.

![Screenshot 2024-11-04 alle 10 16 38](https://github.com/user-attachments/assets/dfc24b99-451f-45be-ba08-15874dd33b35)

This means that users will also use our project ID on other websites (or within MetaMask itself), impersonating our project, consuming our API rate limit, and polluting our stats.

I think this is really bad behavior.

![Screenshot 2024-11-04 alle 10 31 57](https://github.com/user-attachments/assets/90932859-6df3-41d3-a3c6-5dfdc2e2f7d9)

### List of related npm package versions

* @reown/appkit v1.2.1
* @reown/appkit-adapter-wagmi v1.2.1

**Comment by rtomas** [comment]
https://linear.app/reown/issue/APKT-1415/[bug]-switchnetwork-exposes-project-id-and-stores-it-in-user-wallet

**Comment by vittominacori** [comment]
Any (public) discussion?

**Comment by arein** [comment]
We've fixed this - thank you!

**Comment by vittominacori** [comment]
@arein it seems that the project ID is still exposed.

![image](https://github.com/user-attachments/assets/35ad8693-88da-483a-bcdc-72793e6c8efb)
