### ISSUE TITLE
[feature] addNetwork hook needs to be added as it is mentioned in the documentation.

### ISSUE THREAD

**Issue by ARYZEofficial** [reown-com/appkit#3192]
### What problem does this new feature solve?

<img width="802" alt="image" src="https://github.com/user-attachments/assets/0ac650fc-b1d5-48a1-9c81-307f120002b0">

I dont have it in version 1.2.1 
![image](https://github.com/user-attachments/assets/b3f894bb-b7fb-42c7-96b9-2dd4d8f0e069)

![image](https://github.com/user-attachments/assets/62ea4620-efa0-4b7d-9267-08bc51ea1bd4)

### Describe the solution you'd like

i saw you wanted to add this functionality. Please force adding it.

**Comment by rtomas** [comment]
To add a custom network please refer to docs -> https://docs.reown.com/appkit/react/core/custom-networks
