### ISSUE TITLE
[docs] addNetwork not exists and switchNetwork not working when you need to switch to the network which not exist in metamask 

### ISSUE THREAD

**Issue by ARYZEofficial** [reown-com/appkit#3195]
### Summary

I need to switch to network which user dont have yet.
<img width="830" alt="image" src="https://github.com/user-attachments/assets/927b9969-cf5d-463f-8d0a-d8676293acf7">
<img width="939" alt="image" src="https://github.com/user-attachments/assets/f39a250e-9840-4328-9a03-2d30b94e1f42">

addNetwork exist in docs
<img width="845" alt="image" src="https://github.com/user-attachments/assets/e5647736-e746-42a3-91fd-f40e66ae63ef">

but not exists in code
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/044fb7fc-7e56-4d8a-8378-86194baa6146">

<img width="524" alt="image" src="https://github.com/user-attachments/assets/6aaa9c08-fe0b-404b-a555-e473b739f2bd">

### Link to the related docs page

https://docs.reown.com/appkit/next/core/hooks

**Comment by rtomas** [comment]
https://github.com/reown-com/reown-docs/pull/133 -> To delete addNetwork from docs
