### ISSUE TITLE
[bug] Telegram Mini App Sample Does not work

### ISSUE THREAD

**Issue by layinka** [reown-com/appkit#3196]
### Link to minimal reproducible example

https://t.me/appkit_test_ggr_bot

### Summary

The Telegram Mini App Sample does not work inside of telegram.
It can't connect to any of the EVM Wallets i tried, including Trust wallet, Valora, Metamask etc
It triggers the opening of the wallet, but then nothing happens on the wallet and the wallet is not connected to the telegram mini app or some wallets give the following error

```
Webpage not available
The webpage at metamask://wc?uri=wc%253A8d5d9afbbca9cff7801d248f0c519a0316bc3455984fa083c4317deb4c82b2eb%25402%253FexpiryTimestamp%253D1730804932%2526relay-protocol%253Dirn%2526symKey%253D403a677f0c5ee0674802458a4233d37511e0cf5af7cc8d879e89820c1b3eb88a could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME
```

### List of related npm package versions

https://t.me/appkit_test_ggr_bot

**Comment by rtomas** [comment]
HI @layinka 

Would you mind sharing with me more information about your issue ?

Can you make a video to see where are you having this issue ?

Thanks

**Comment by layinka** [comment]
Link

https://youtu.be/hSgmRnPFUZY?si=XmucQyTjzbNRIJHX

**Comment by layinka** [comment]
Hi @rtomas 

Any Luck with this?

**Comment by rtomas** [comment]
Do you have metamask installed in your cellphone ? which version ?

cc @ganchoradkov

**Comment by layinka** [comment]
Yes i do.
Metamask (Latest version ) on android

**Comment by arein** [comment]
Can you upgrade to latest @layinka ?
