### ISSUE TITLE
[bug] Metamask connection error [CRITICAL]

### ISSUE THREAD

**Issue by vis1onn** [reown-com/appkit#3198]
### Link to minimal reproducible example

this.metadata = {       name: document.title,       description: 'Web3 Application',       url: `https://${window.location.host}`,       icons: ['https://avatars.githubusercontent.com/u/179229932'],     };      this.modal = createAppKit({       adapters: [new EthersAdapter()],       networks: [         mainnet,         bsc,         polygon,         avalanche,         arbitrum,         optimism,         fantom,         base,         zkSync,       ],       metadata: this.metadata,       projectId: import.meta.env.VITE_APPKIT_PROJECT_ID,       features: {         email: false,         socials: [],         analytics: true,         debug: true,       },       debug: true,     });

### Summary

MetaMask no longer injects web3. For details, see: https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3

The option to connect metamask has disappeared from the list of options
![image](https://github.com/user-attachments/assets/dbdcf97a-b389-4c6e-9b28-aa632c02340a)

an error appeared in the console
![image](https://github.com/user-attachments/assets/384a6f1e-bb47-488f-8c18-d34a528624ef)

20 minutes ago everything worked
no changes were made, it just stopped working with this error

not working also with 1.1.8 version

### List of related npm package versions

  "@reown/appkit": "^1.2.1",
    "@reown/appkit-adapter-ethers": "^1.2.1",

**Comment by tomiir** [comment]
@vis1onn Thank you for the report. 
Will relay this to cloud team to review if something is off with the explorer where we get the wallets from. 

Question: What network were you on when this happened? This might help debug this 🙏 

Also reported the comment above. 🫡

**Comment by vis1onn** [comment]
@tomiir thanks for the help, I didn't find what the problem was, but I found that only I have this problem
