### ISSUE TITLE
[bug] WagmiAdapter to correctly infer wagmiConfig type

### ISSUE THREAD

**Issue by AzzouQ** [reown-com/appkit#3224]
### Link to minimal reproducible example

https://stackblitz.com/edit/viem-getting-started-dqqqdr?file=index.ts

### Summary

When using the `WagmiAdapter`, we can access the wagmi config by doing `wagmiAdapter.wagmiConfig` [as stated in the documentation](https://docs.reown.com/appkit/next/core/installation#wagmi-config) . However, `wagmiAdapter.wagmiConfig` doesn't leverage generics from wagmi's `createConfig`.

```ts
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { createConfig, http } from 'wagmi';
import { arbitrum, sepolia } from 'viem/chains';

const wagmiAdapter = new WagmiAdapter({
  projectId: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID!,
  networks: [arbitrum, sepolia],
});

// Poorly typed: Config
wagmiAdapter.wagmiConfig;

const config = createConfig({
  chains: [arbitrum, sepolia],
  transports: {
    [arbitrum.id]: http(),
    [sepolia.id]: http(),
  },
});

// Strongly typed: Config<chains, transport>
config;

declare module 'wagmi' {
  interface Register {
    config: typeof wagmiAdapter.wagmiConfig; // Won't work because the type is not correctly inferred
  }
}
```

Doing so prevent strong type-safety [as stated in wagmi's documentation](https://wagmi.sh/react/typescript#config-types).

Could it be possible for the `WagmiAdapter` to take those in consideration ?

### List of related npm package versions

@reown/appkit: ^1.3.1
@reown/appkit-adapter-wagmi: ^1.3.1
viem: 2.21.44
wagmi: 2.12.29

**Comment by AzzouQ** [comment]
I'm actually using the following workaround to mimic wagmi's `createConfig` behavior in `WagmiAdapter`

```ts
declare class WagmiAdapter<
  const networks extends readonly [AppKitNetwork, ...AppKitNetwork[]]
> implements ChainAdapter {
  public wagmiChains: networks;
  public wagmiConfig: AdapterOptions<Config<networks>>['wagmiConfig'];
  public constructor(configParams: Partial<CreateConfigParameters> & {
    networks: networks;
    projectId: string;
});
```

It does the tricks for me since I only use Viem's chain, but I guess it wouldn't work with the Solana network.

**Comment by AzzouQ** [comment]
May be realted to #2823

**Comment by arein** [comment]
Wagmi doesn't support Solana - looks like you found a workaround - curious @AzzouQ what app are you building?

**Comment by AzzouQ** [comment]
You are totally right, Wagmi and Solana are not related as it is handled by 2 differents adaptaters.

Still the issue remain, i'm not sure why you closed it. The `WagmiAdapter` doesn't leverage generics from wagmi's `createConfig`, which prevent strong type-safety [as stated in wagmi's documentation](https://wagmi.sh/react/typescript#config-types).

**Comment by mlenser** [comment]
@AzzouQ Are you still using this solution? Can you give a full example? We can't find `AdapterOptions` anywhere.

**Comment by c0rdeiro** [comment]
yeah, still trying to figure this out as well
