### ISSUE TITLE
[feature] Check the wallet balance in the view and it is 0,HTTP Req 404

### ISSUE THREAD

**Issue by Jacky-Young1123** [reown-com/appkit#3225]
### What problem does this new feature solve?

When I used JavaScript to integrate appkit, the following error occurred.
Request address: https://rpc.walletconnect.org/v1/account/F9hEqGcPRudRn2SNCDFYL2XoTQk16ra2YcBkvjC7hcVp/balance?currency=usd&projectId=
{projectId}&chainId=5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp&clientId=did%3Akey%3Az6MkiQ758M4AvTgujLn2RpvN5jepDWXtq1sk7k2wkPNuW
![image](https://github.com/user-attachments/assets/b16ee987-d45b-4f38-b5a8-81715f993fb6)
![image](https://github.com/user-attachments/assets/fafa49e4-02f4-4866-bfb6-4d3095216e9f)

Error message: {status: "FAILED", reasons: [{field: "address", description: "The address provided is invalid"}]}
reasons: [{field: "address", description: "The address provided is invalid"}]0: {field: "address", description: "The address provided is invalid"} description: "The address provided is invalid" field : "address" status : "FAILED"
![image](https://github.com/user-attachments/assets/6935f580-34a6-4631-b3ae-5961e4db2b02)

And check the wallet balance in the view and it is 0
![image](https://github.com/user-attachments/assets/58b4a5e1-0337-434b-b70f-bbcf96e0c4c9)

### Describe the solution you'd like

Can this problem be solved?

**Comment by mits87** [comment]
Same issue here for testnets for example arbitrum sepolia: 

<img width="764" alt="image" src="https://github.com/user-attachments/assets/c7b80b88-da76-40c0-be49-69eb9774b172">

<img width="914" alt="Screenshot 2024-11-11 at 12 48 39" src="https://github.com/user-attachments/assets/f91825fb-d3f9-43ba-88df-bf10da05572b">

**Comment by Emmaward090** [comment]
> ### What problem does this new feature solve?
> When I used JavaScript to integrate appkit, the following error occurred. Request address: https://rpc.walletconnect.org/v1/account/F9hEqGcPRudRn2SNCDFYL2XoTQk16ra2YcBkvjC7hcVp/balance?currency=usd&projectId= {projectId}&chainId=5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp&clientId=did%3Akey%3Az6MkiQ758M4AvTgujLn2RpvN5jepDWXtq1sk7k2wkPNuW ![image](https://private-user-images.githubusercontent.com/171530490/384770543-b16ee987-d45b-4f38-b5a8-81715f993fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjY4MDQsIm5iZiI6MTczMTMyNjUwNCwicGF0aCI6Ii8xNzE1MzA0OTAvMzg0NzcwNTQzLWIxNmVlOTg3LWQ0NWItNGYzOC1iNWE4LTgxNzE1Zjk5M2ZiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjAxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjI2Y2ExMTFlYzEzZGMyN2FiZGZlZGI1MTM1ZWVkM2MxNmE0YWEyNGU1MTkyZDY5YWFhMDU5NzNmNDY2YzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8dU8wVyh710Fkwo-S26H4ga5DJNm4S_XAk36AURyL6I) ![image](https://private-user-images.githubusercontent.com/171530490/384770612-fafa49e4-02f4-4866-bfb6-4d3095216e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjY4MDQsIm5iZiI6MTczMTMyNjUwNCwicGF0aCI6Ii8xNzE1MzA0OTAvMzg0NzcwNjEyLWZhZmE0OWU0LTAyZjQtNDg2Ni1iZmI2LTRkMzA5NTIxNmU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjAxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmVmMjAxYjM5MWFjOGI1NjdiMTc0YzdiNTZjZjM0ODFkODdhNGE3ODY5MjZkOTAyNGUyN2UzMDg5NTA2ODk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WtQtBJTUwbxJt2ee8jBlcZxf9brYdCdWV9uk73C5x9c)
> 
> Error message: {status: "FAILED", reasons: [{field: "address", description: "The address provided is invalid"}]} reasons: [{field: "address", description: "The address provided is invalid"}]0: {field: "address", description: "The address provided is invalid"} description: "The address provided is invalid" field : "address" status : "FAILED" ![image](https://private-user-images.githubusercontent.com/171530490/384770661-6935f580-34a6-4631-b3ae-5961e4db2b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjY4MDQsIm5iZiI6MTczMTMyNjUwNCwicGF0aCI6Ii8xNzE1MzA0OTAvMzg0NzcwNjYxLTY5MzVmNTgwLTM0YTYtNDYzMS1iM2FlLTU5NjFlNGRiMmIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjAxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTU3OTMzYzdhNGU3Y2Y3MDllZjBhNmZiMmU3NWZhZTIzNDljYzBiMTUyNGZiZjc0ZGYwMjNhYjA0OWY2Y2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hzEjhSm4bKlqs-telZ8XRXyAJhzVrH9JAlNS-lnX8cc)
> 
> And check the wallet balance in the view and it is 0 ![image](https://private-user-images.githubusercontent.com/171530490/384770881-58b4a5e1-0337-434b-b70f-bbcf96e0c4c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjY4MDQsIm5iZiI6MTczMTMyNjUwNCwicGF0aCI6Ii8xNzE1MzA0OTAvMzg0NzcwODgxLTU4YjRhNWUxLTAzMzctNDM0Yi1iNzBmLWJiY2Y5NmUwYzRjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMjAxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGM5YjdmNzgxN2Y2OThlZDQzZDk4YjdiZWNjYTQyNDNiY2JmNTU4NWI1YjdiNWZlMGYyOThiN2UzODliOTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y90rJP_fI_DElbDsKcBwpWNzlFNW2Y3SWKiwToEhtKE)
> 
> ### Describe the solution you'd like
> Can this problem be solved?


It seems like you're encountering an error related to an invalid address when trying to check the wallet balance using JavaScript and Appkit integration. The error message indicates that the address provided is considered invalid, leading to a failed status. This could be the reason why the wallet balance is showing as 0 in the view. Double-check the address you're using and ensure it's correctly formatted to avoid this issue. If you need further assistance with resolving this, feel free to share more details! @Jacky-Young1123 @mits87

**Comment by mits87** [comment]
What do you mean by invalid address? 
I'm connecting to the metmask wallet and there I have all money in arbitrum sepolia. 

Btw. Few versions ago I didn't see this error even if I used the same wallet.

**Comment by vanyasav** [comment]
Same issue here, after updating to 1.3.2 
![image](https://github.com/user-attachments/assets/97821a37-78ce-4b03-95eb-0ae566a7194f)

https://github.com/vanyasav/angular-reown-wagmi/tree/fetch_error

**Comment by Beor18** [comment]
Same problem

**Comment by rtomas** [comment]
Where are working on a fix ... will be available soon.

**Comment by rtomas** [comment]
https://linear.app/reown/issue/APKT-1440/%5Bbug%5D-err-400-when-getting-balance-from-solana

**Comment by rtomas** [comment]
Please update to latest. V1.4.0
