### ISSUE TITLE
[bug] Blocked a frame with origin "capacitor://localhost"

### ISSUE THREAD

**Issue by reslear** [reown-com/appkit#3232]
### Link to minimal reproducible example

no need

### Summary

![CleanShot 2024-11-12 at 15 54 43@2x](https://github.com/user-attachments/assets/a280bf15-9781-4eca-901e-cac05b15e235)

When attempting to access a frame with origin https://verify.walletconnect.org from a frame with origin capacitor://localhost, the operation is blocked due to a protocol mismatch between the two frames. Specifically, capacitor protocol cannot access resources with the https protocol, causing cross-origin restrictions to prevent the connection.

https://ionicframework.com/docs/troubleshooting/cors

Also added to console 

![CleanShot 2024-11-12 at 17 06 43@2x](https://github.com/user-attachments/assets/93fcada4-2900-4329-9355-6a3e895d2dd1)

### List of related npm package versions

latest

**Comment by arein** [comment]
@reslear apologies - @Cali93 can you take a look pls?

**Comment by arein** [comment]
We don't have a way right now to verify desktop apps - wallets connecting to your desktop app will show "unverified domain" - @reslear what kind of app are you building?

**Comment by reslear** [comment]
@arein we build just Dapp with [capacitor](https://capacitorjs.com/)

**Comment by reslear** [comment]
@arein pls reopen, because problem actual, and say please for wc team and maybe move to https://github.com/WalletConnect/walletconnect-monorepo
