### ISSUE TITLE
[bug] empty explorer api dapps list 

### ISSUE THREAD

**Issue by r-oman-G** [reown-com/appkit#3235]
### Link to minimal reproducible example

https://explorer-api.walletconnect.com/v3/dapps?projectId=your_project_id

### Summary

I'm trying to retrieve a list of dApps using the WalletConnect Explorer API, but I'm encountering an issue. When I make the following call:

`https://explorer-api.walletconnect.com/v3/dapps?projectId=your_project_id`
I consistently receive an empty response: {"listings":{},"count":0,"total":0}. Based on the documentation, I expected this request to return a populated list of dApps.

Is there an issue with this API endpoint, or am I missing any required configurations or permissions for my project ID? Any guidance on resolving this would be greatly appreciated.

The documentation: https://docs.reown.com/cloud/explorer

Thank you!

### List of related npm package versions

It's API question

**Comment by arein** [comment]
@r-oman-G this list depends on the chain ID - why are you directly calling our API? If you don't rely on AppKit to consume the UI please get in touch to make sure we support your usecase
