### ISSUE TITLE
[bug] METAMASK CONNECT FAILED: ConnectorController.setConnectors: Not possible to add connector

### ISSUE THREAD

**Issue by vis1onn** [reown-com/appkit#3244]
### Link to minimal reproducible example

https://codesandbox.io/p/sandbox/cranky-sara-m9n7qz?workspaceId=a5758ebb-9135-49f0-b708-70855cec901f

### Summary

![image](https://github.com/user-attachments/assets/a5f2027f-6140-4626-9b87-14e93be37b80)

At the moment, there are three conditions in which I cannot connect to Metamask, since the modal window shows that the wallet is not installed

1. Using any iframe on the site that loads before the initialization of the modal connection window - causes an error as shown in the screenshot. Attached a sundbox with reproduction of this bug.
2. Also encountered a similar problem but with GTM. If GTM loads before the connection window - I see the absence of a wallet. Most likely because GTM adds something like a pixel that integrates the iframe to track user actions. so i think its the same case (look at point 1)
3. I also encountered a very strange problem associated with the number of reactive variables in the application. In my case, I added the connection window dynamically - after certain actions, and when my application became much larger (there were more reactive variables), Metamask stopped displaying. I received an error of this format
![image](https://github.com/user-attachments/assets/ad7ad570-7d43-4fea-8c36-1ae32bdb75f1)

Problem number 3 will be quite difficult to reproduce, but perhaps it is all somehow connected. And unfortunately I can't show my code so that you can study it

The problem is very critical and I hope it will be solved as soon as possible.

### List of related npm package versions

tested on all latest versions, nothing works

 "@reown/appkit": "^1.4.0",
 "@reown/appkit-adapter-ethers": "^1.4.0",

**Comment by vis1onn** [comment]
same issue https://github.com/reown-com/appkit/issues/3198

**Comment by vis1onn** [comment]
here is a more detailed description of case number 3

- there is a Vue3 application
- after certain actions, the Vue3 app dynamically loads an ESM script into the body, which integrates a modal window for connecting a wallet
`const script = document.createElement("script");
script.src = 'esm script to connect wallet';
document.body.appendChild(script);`
- here is how esm scipt looks like
`
import { createAppKit } from '@reown/appkit';
import { EthersAdapter } from '@reown/appkit-adapter-ethers';
import {
  mainnet,
  bsc,
  polygon,
  avalanche,
  arbitrum,
  optimism,
  fantom,
  base,
  zkSync,
} from '@reown/appkit/networks';
const modal = createAppKit({...})
modal.open()
`

**Comment by vis1onn** [comment]
@rtomas hey!
I appreciated your help when you worked at web3auth
I would appreciate some help here

**Comment by rtomas** [comment]
https://linear.app/reown/issue/APKT-1463/[bug]-mematask-not-showing-on-ethers (internal)

**Comment by s-pcode** [comment]
Hey, I'm also facing the same issue where using ethersv5 does not detect the installed metamask extention. The example dapp also has the same issue - https://appkit-lab.reown.com/library/ethers5/.
