### ISSUE TITLE
[bug] Email login stopped working on localhost

### ISSUE THREAD

**Issue by thomasvalera** [reown-com/appkit#3249]
### Link to minimal reproducible example

https://github.com/thomasvalera/AppKit-Multiline-Siwe

### Summary

Hey all! 

I've been using AppKit on localhost for a few months now and it's been working fine but for some reason this morning it suddenly started throwing an error:

> Origin http://localhost:5174 not found on Allowlist - update configuration to enable social login

I reverted back to previous commits and tried with the example project AppKit-Siwe but it throws the same error.

Also tried adding http://localhost:5174 as domain of course, updating to the latest AppKit version but it doesn't seem to change anything.

Is anyone else experiencing this issue?

### List of related npm package versions

@reown/appkit 1.1.2
@reown/appkit-adapter-wagmi 1.1.2
@reown/appkit-siwe 1.1.2
@wagmi/core 2.13.8
viem 2.21.26
wagmi 2.12.17

**Comment by aminhdev** [comment]
You can try with https protocol, for example https://localhost:5174

**Comment by rtomas** [comment]
it's working ok. please ping me if your problem persist
