### ISSUE TITLE
[bug] Coinbase wallet not connecting to appkit lab

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3255]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi/

### Summary

I attached a video where I am trying to connect to appKit lab with coinbase wallet and nothing happens

https://github.com/user-attachments/assets/7dd61276-112c-4e32-acc8-2411ab070632

### List of related npm package versions

Wagmi on appKit lab

**Comment by Elsonbastey** [comment]
> ### Link to minimal reproducible example
> https://appkit-lab.reown.com/library/wagmi/
> 
> ### Summary
> I attached a video where I am trying to connect to appKit lab with coinbase wallet and nothing happens
> 
>  Screen_Recording_20241118_145402_Chrome.mp4 
> ### List of related npm package versions
> Wagmi on appKit lab

Hello @vanyasav 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LAB106338
Please see the link below to our dedicated support line:
[Coinbase Wallet DApps Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by arein** [comment]
@vanyasav Coinbase often has issues - it took me 3 attempts but then it ended up working - we have open bug reports with them - please just in case update AppKit to latest
