### ISSUE TITLE
[bug] Modal not responding to switching network after choosing unsupported network in a wallet

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3264]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi/

### Summary

1. Connect a wallet
2. Switch network in the wallet
3. Modal appears on a screen
4. Clicking on the first item in the list has no response

[Screencast from 19-11-2024 10:25:29.webm](https://github.com/user-attachments/assets/6e0afb41-ed74-4dcc-ad6a-f7489b54fd5c)

### List of related npm package versions

Appkit lab

**Comment by vanyasav** [comment]
related to #3129

**Comment by svenvoskamp** [comment]
Thanks for reporting. This has been resolved in our latest release `1.5.3`
