### ISSUE TITLE
[bug] Less options for theming w3-button and w3-network-button

### ISSUE THREAD

**Issue by nazlul** [reown-com/appkit#3314]
### Link to minimal reproducible example

not deployed currently

### Summary

There isn't much theming available in themeVariables. I'm able to change the color of modal and connect button before connecting using  '--w3m-color-mix' and '--w3m-accent'. But thats it, I couldn't find a way to change the color of the network button, button after connecting or the color of text

### List of related npm package versions

reown version 10.7.0

**Comment by rtomas** [comment]
The projectId of the projectId is wrong. Anyone can get one in http://cloud.reown.com

**Comment by rtomas** [comment]
We are working on better customization. Anyway you can create you own button and open the modal using our hook -> https://docs.reown.com/appkit/react/core/hooks#useappkit
