### ISSUE TITLE
[bug]  Problem connecting the wallet

### ISSUE THREAD

**Issue by Beor18** [reown-com/appkit#3318]
### Link to minimal reproducible example

https://drive.google.com/file/d/1KRnlSMo1txaSlo_b1dBGYVa5Qy7iNj3L/view?usp=sharing

### Summary

Hello, when trying to connect the wallet it gives me the following error.

Taking into account that I already have the projectId set

**Bad Request** - projectId must be 32 characters long, Invalid. Required headers: x-project-id, x-sdk-type, x-sdk-version

### List of related npm package versions

 "@reown/appkit": "^1.5.1",

**Comment by rtomas** [comment]
The projectId is wrong. Anyone can get one in http://cloud.reown.com

**Comment by Beor18** [comment]
> The projectId is wrong. Anyone can get one in http://cloud.reown.com

I have already managed to do it several times there and the same error occurs no matter how many projectIds I have.

**Comment by Beor18** [comment]
The problem was that there were dependencies left without updating

Thanks solved!
