### ISSUE TITLE
[feature] Request to support Etherlink (XTZ)

### ISSUE THREAD

**Issue by rhamnett** [reown-com/appkit#3321]
### What problem does this new feature solve?

Hello, when manually adding the EVM compatible network Etherlink, there is no balance update. Hoping this should be relatively easy to add so I don't have to keep my manual balance check implementation in the longer term.

2024-11-24 21:02:27.811074 ❌ [BlockChainService] getBalance, decode result error => Exception: We don't support the chainId you provided: eip155:42793. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains

Here are Etherlink's chain details:

https://docs.etherlink.com/get-started/network-information/

| Parameter                  | Value                                   |
|----------------------------|-----------------------------------------|
| Network Name               | Etherlink Mainnet                      |
| EVM version                | Shanghai                               |
| RPC Endpoint               | https://node.mainnet.etherlink.com     |
| Relay Endpoint             | https://relay.mainnet.etherlink.com    |
| Chain ID                   | 42793                                  |
| Currency Symbol            | XTZ                                    |
| Block Explorer URL         | https://explorer.etherlink.com         |

### Describe the solution you'd like

Implement Etherlink EVM compatible support

**Comment by arein** [comment]
Please follow https://docs.reown.com/cloud/chains/overview

**Comment by rhamnett** [comment]
> Please follow https://docs.reown.com/cloud/chains/overview

Hello. I've already done this but the getBalance function does not work hence the ticket. I've implemented a workaround but am I missing something? Cheers
