### ISSUE TITLE
[docs] web3Modal.adapter is undefined when trying to disconnect

### ISSUE THREAD

**Issue by linxuanweb** [reown-com/appkit#3325]
### Summary

**Doc Referrence**
[https://docs.reown.com/appkit/javascript/core/actions#disconnect](https://docs.reown.com/appkit/javascript/core/actions#disconnect)

**Description**
I am using `@reown/appkit` and encountered an issue where web3Modal.adapter is undefined when attempting to call `disconnect()`. The wallet connection works fine, and the WalletConnect modal successfully displays the connected account. However, clicking the "Disconnect" button logs undefined for the adapter, making it impossible to disconnect the wallet.

The code is based on the official documentation.

```
import { createAppKit } from "@reown/appkit";
import { EthersAdapter } from "@reown/appkit-adapter-ethers";
import { bsc, mainnet } from "@reown/appkit/networks";

const projectId = "xxx";

const metadata = {
  name: "xxx",
  description: "xx",
  url: "https://xx.io",
  icons: ["https://xxxx.io/favicon.ico"],
};

const web3Modal = createAppKit({
  adapters: [new EthersAdapter()],
  networks: [mainnet, bsc],
  allowUnsupportedChain: true,
  metadata,
  projectId,
  features: {
    analytics: true, // Optional - defaults to your Cloud configuration
    socials: false,
    email: false,
  },
});

document.getElementById("connect").addEventListener("click", () => {
  web3Modal.open();
});

document.getElementById("disconnect").addEventListener("click", () => {
  console.log(web3Modal.adapter);
  web3Modal.adapter?.connectionControllerClient?.disconnect();
});
```

**Actual Result**
web3Modal.adapter is undefined after clicking the "Connect" button and attempting to disconnect.

**Expected Behavior**
After connecting the wallet, web3Modal.adapter should be properly initialized. Calling`web3Modal.adapter?.connectionControllerClient?.disconnect()` should successfully disconnect the wallet.

**Actual Behavior**
Calling `web3Modal.adapter?.connectionControllerClient?.disconnect()` fails because web3Modal.adapter is undefined.

**Environment**
```
  "dependencies": {
    "@reown/appkit": "^1.4.1",
    "@reown/appkit-adapter-ethers": "1.4.1",
    "ethers": "^6.13.4",
    "vite": "^5.4.11"
  }
```
Node.js version: 20.18.0

### Link to the related docs page

https://docs.reown.com/appkit/javascript/core/actions#disconnect

**Comment by svenvoskamp** [comment]
Could you try using `await modal.disconnect()` , we will be updating the docs
