### ISSUE TITLE
[bug] Appkit does no longer allow to switch to an unsupported chain in the wallet with allowUnsupportedChain set to true

### ISSUE THREAD

**Issue by paintoshi** [reown-com/appkit#3340]
### Link to minimal reproducible example

https://stackblitz.com/edit/stackblitz-starters-36aam4?file=context%2Findex.tsx

### Summary

With web3modal v5.1.9 it was possible to use `allowUnsupportedChain: true` in the createWeb3Modal. Then switch to another chain in the wallet, while still using the application.

With appkit, has that option been removed? When I switch network in rabby, a modal pops up blocking the whole application. This makes our app impossible to use since we have an integrated swap widget that needs to switch to other networks during the swap. While the application surrounding it only supports one network. I can't migrate to appkit for this reason.

```
createAppKit({
  adapters: [wagmiAdapter],
  networks: [mainnet],
  metadata,
  projectId,
  allowUnsupportedChain: true,
});
```

I supplied a project on stackblitz but it can't be tested there since the application won't detect wallet switches. Need to be downloaded and run locally.

`yarn install`
`yarn dev`

See this video:

https://github.com/user-attachments/assets/e452f814-6cca-484a-bd4e-29833c537852

Looking at the old code I see it being referenced here (as in it won't display the modal if that param is set): https://github.com/reown-com/appkit/blob/V5/packages/core/src/controllers/NetworkController.ts#L121

But in the new code the whole NetworkController.ts has been removed and I can't find any reference to allowUnsupportedChain being used (when searching the whole repo). It seems the parameter is straight ignored here: https://github.com/reown-com/appkit/blob/main/packages/core/src/controllers/ChainController.ts#L222

------------
Another issue is after switching to a supported network, which Rabby handles automatically, the modal does not close. Minor UX issue. Seen at the end of the video.

### List of related npm package versions

"@reown/appkit": "^1.5.2",
"@reown/appkit-adapter-wagmi": "^1.5.2",
"@tanstack/react-query": "^5.61.4",
"next": "13.5.1",
"react": "18.2.0",
"viem": "^2.21.51",
"wagmi": "^2.13.0"

**Comment by vanyasav** [comment]
Same issue

**Comment by arein** [comment]
@vanyasav @paintoshi apologies for this - @Sam-Newman can you please triage?

**Comment by arein** [comment]
Just double-checking - @vanyasav @paintoshi why is disclosing more networks not an option to support the swap?

Because you'd need to disclose all networks the user might have?

Can we try your existing app somehow to confirm?

**Comment by rtomas** [comment]
hi @paintoshi, changed this issue to a feature-request. I will be discussing with the team to try to find a good solution.

**Comment by arein** [comment]
@paintoshi @vanyasav we just fixed this in  https://github.com/reown-com/appkit/pull/3447 

It will be in the next release ~today or Monday
