### ISSUE TITLE
SIWE on React package not persist after reload 

### ISSUE THREAD

**Issue by Another-DevX** [reown-com/appkit#3349]
### Link to minimal reproducible example

https://github.com/reown-com/web-examples/tree/main/dapps/appkit-siwe/react

### Summary

After the user completes the signature and gets verified, the session should persist even if the user reloads the page, as managed by Next.js with NextAuth. However, currently, it does not, and the sign modal reopens.

(I tried with the previous version and the latest of all the packages on the examples repo)

### List of related npm package versions

    "@reown/appkit": "1.5.2",
    "@reown/appkit-adapter-wagmi": "1.5.2",
    "@reown/appkit-siwe": "1.4.1",
    "@wagmi/core": "^2.13.
    "wagmi": "^2.13.2"

**Comment by Another-DevX** [comment]
[Screencast from 2024-11-27 19-39-01.webm](https://github.com/user-attachments/assets/c8682c79-96e7-4251-a729-743b1cf509df)

**Comment by rtomas** [comment]
please check our docs and examples again. We fix them. sorry for the inconvenience . 🫶

- https://docs.reown.com/appkit/react/core/siwe
- https://github.com/reown-com/web-examples/tree/main/dapps/appkit-siwe
