### ISSUE TITLE
[bug] IOS 17.*+ MetaMask wallet Sign typed data not working after wallet connection from the mobile browser for wagmi + AppKit

### ISSUE THREAD

**Issue by sashka2131** [reown-com/appkit#3357]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi-no-email/

### Summary

**Expected behaviour:**
User with IOS 17.* and above opens web app link in browser -> User connect MM wallet -> User press "Sign Typed Data" -> Sign Typed Data modal appear in the MM app -> User confirm Sign -> User returns to the browser and see Success message

From IOS 17.* MetaMask stopped automatically redirect user back to the web app, because of OS changes under the hood (check [the link](https://github.com/MetaMask/metamask-mobile/issues/8003#issuecomment-1957779002) to the MetaMask contributor comment on such issue ) to continue wallet connection flow or just use app with connected wallet.

So for now on IOS 17+ when user trying to connect wallet and confirm it in the MetaMask the "Return to app" Modal appears, user manually goes back to the browser and see that he is connected. 
But then I need user to sign the message (Sign typed data) as a part of Auth flow. I'm calling method to request sign from user, browser requests user to allow opening of MM app and when user navigate to the MM app there is still visible modal "Return to app" and MM tries to process Signature request and nothing happens or MM throws error wrong chain and when user returns to the web app it says that user declined sign request.

P.S. On Android phones or Iphone with <17 IOS such issue not reproduces. Also attaching video of current behaviour on IOS 17+ from reproducible demo mentioned above. Would be glad if you can help me to solve this issue.

Config for wallet connection flow:
```
import { createAppKit } from '@reown/appkit/react'
import { http, WagmiProvider } from 'wagmi'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { AppKitNetwork, polygonAmoy, sepolia } from '@reown/appkit/networks'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import logo from 'assets/images/logo-sm.svg'

const queryClient = new QueryClient()

const includeWalletIds = [
  // MetaMask public id
  'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96'
]

const metadata = {
  name: 'AppName',
  description: 'AppDescription',
  url: window.location.href,
  icons: [logo]
}

const generalConfig = {
  projectId: '***',
  metadata,
  networks: [polygonAmoy, sepolia] as [AppKitNetwork, ...AppKitNetwork[]]
}

const wagmiAdapter = new WagmiAdapter({
  ...generalConfig,
  transports: {
    [sepolia.id]: http(`https://sepolia.infura.io/v3/${INFURA_KEY}`),
    [polygonAmoy.id]: http(
      `https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_KEY}`
    )
  }
})

createAppKit({
  ...generalConfig,
  adapters: [wagmiAdapter],
  features: {
    email: false,
    socials: false
  },
  enableCoinbase: false,
  allWallets: 'ONLY_MOBILE',
  defaultNetwork: polygonAmoy,
  includeWalletIds: includeWalletIds,
  featuredWalletIds: includeWalletIds
})

const AppKitProvider = ({ children }: any) => {
  return (
    <WagmiProvider config={wagmiAdapter.wagmiConfig}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </WagmiProvider>
  )
}

export default AppKitProvider
```

https://github.com/user-attachments/assets/6d347853-e9a6-4428-80df-fe78dc89ec94

### List of related npm package versions

```
"@reown/appkit": "1.5.2",
"@reown/appkit-adapter-wagmi": "1.5.2",
"@tanstack/react-query": "5.60.2",
"wagmi": "2.12.32",

"react": "18.3.1",
"typescript": "5.6.3",
"vite": "5.4.11",
```

**Comment by arein** [comment]
@sashka2131 you need to report this with MetaMask unfortunately - the intel we have is that they will support multichain behavior in Q1 2025
