### ISSUE TITLE
[feature] Lens V3 Smart Account Onboarding

### ISSUE THREAD

**Issue by hroyo** [reown-com/appkit#3361]
### What problem does this new feature solve?

Lens Network (zk chain) is launching, profiles will now be native smart account (embedded zkSynch) 

We have so far been loving reown sociial sign in and account abtrasction to onboard new users. 
However now that account abstraction is native to Lens Network chain, we believe it would be redondant for new users to have to create 2 smart accounts (one with lens and one with reown). 

### Describe the solution you'd like

We would like to see native integration of Lens Account into the reown wallet for a seamless ONE CLICK Lens account onboarding with reown.

**Comment by hroyo** [comment]
https://dev-preview.lens.xyz/docs/features/authentication

**Comment by arein** [comment]
@hroyo please provide a 1Pager that scopes out the integration in a bit more consumable detail via Telegram/Slack via our existing channels - this is a large task and the docs you link don't shine enough light enabling us to quickly assess the scope
