### ISSUE TITLE
[bug] const { address, isConnected } = useAppKitAccount() cannot be destructured and prompts undefined

### ISSUE THREAD

**Issue by harvey-blake** [reown-com/appkit#3364]
### Link to minimal reproducible example

https://docs.reown.com/appkit/vue/core/installation

### Summary

![image](https://github.com/user-attachments/assets/17e37ac1-e1e7-4607-8c71-aa38e1051d90)

<template>
  <div><appkit-button /></div>

  <a-button @click="bug()">bug</a-button>
</template>
<script setup>
  import { watch } from "vue";
  import { modal } from "@/api/web3ModalConfig";
  import { useAppKitProvider, useAppKitAccount } from "@reown/appkit/vue";
  const { address, isConnected } = useAppKitAccount();
  const bug = async () => {
    console.log(useAppKitAccount());
    console.log(address, isConnected);
  };
</script>

According to the documentation, it cannot be deconstructed and the prompt is undefined. I am using VUE3.

### List of related npm package versions

 "@reown/appkit": "^1.5.3",
   "@reown/appkit-adapter-ethers": "^1.5.3",
    "@reown/appkit-siwe": "^1.5.1",
    "@walletconnect/modal-core": "^2.7.0",
    "@walletconnect/modal-ui": "^2.7.0",

**Comment by enesozturk** [comment]
@harvey-blake We are suggesting users to use the following method on our docc. You shouldn't have problem to ready to values when not doing destructing. We are already working on a refactor to provide descruction feature on our Composables. 
```js
import { useAppKitAccount } from "@reown/appkit/vue";

export default Component(){
  const accountData = useAppKitAccount()
}
```

Docs: https://docs.reown.com/appkit/vue/core/composables#useappkitaccount
