### ISSUE TITLE
[bug] Sign In With Ethereum: Automatically triggers logout after signing in with metamask.

### ISSUE THREAD

**Issue by adityabhattad2021** [reown-com/appkit#3369]
### Link to minimal reproducible example

https://github.com/StabilityNexus/FairFund/tree/reown-update

### Summary

Sign with with Ethereum implementation does not works as expected. 
1. I click connect wallet
2. Metamask gets connected
3. Asks to sign in with Ethereum
4. Sign the transaction
5. After I sign, it asks to change the network
6. I change the network 
7. It automatically trigger the signout function

### List of related npm package versions

 "@reown/appkit": "1.5.2",
 "@reown/appkit-adapter-wagmi": "1.5.2",
 "@reown/appkit-siwe": "^1.5.2",

### Node.js Version

20.11.1

### Package Manager

10.5.1

**Comment by arein** [comment]
I am not able to reproduce on https://appkit-lab.reown.com/library/wagmi-siwe/ which uses v1.6.0

@adityabhattad2021 can you pls try upgrading to 1.6.0 and reopen the issue if it doesn't work?
