### ISSUE TITLE
[bug] Unable to get signer after logging in with social account

### ISSUE THREAD

**Issue by shunz19** [reown-com/appkit#3386]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/ethers/

### Summary

Calling ```provider.getSigner()``` throws an error:
![image](https://github.com/user-attachments/assets/9ae5ccf3-91e0-4902-ae67-339596757157)

Calling ```open({ view: "Account"});``` and switching to a non smart account one, then ```provider.getSigner()``` works fine.
![image](https://github.com/user-attachments/assets/55508ec1-b365-4186-ab44-6c34e3f16f94)
![image](https://github.com/user-attachments/assets/bc472b5f-4a5b-4dc1-8038-8365e66bbced)

### List of related npm package versions

		"@reown/appkit": "^1.5.3",
		"@reown/appkit-adapter-ethers": "^1.5.3",
		"ethers": "^6.13.2",

### Node.js Version

v20.14.0

### Package Manager

pnpm@9.4.0

**Comment by arein** [comment]
Discussed in Discussions - closing here
