### ISSUE TITLE
[docs] WagmiConfig is deprecated

### ISSUE THREAD

**Issue by jackleeio** [reown-com/appkit#3396]
### Summary

`WagmiConfig` is deprecated
should use `WagmiProvider` instead

https://docs.reown.com/appkit/upgrade/to-reown-appkit-web#web3modal-v5-to-reown-appkit---web--wagmi

```
export default function App() {
  return (
    <>
     <WagmiConfig config={wagmiAdapter.wagmiConfig}>
      <QueryClientProvider client={queryClient}>
          <HomePage />
       </QueryClientProvider>
      </WagmiConfig>
    </>
)}
```

### Link to the related docs page

https://docs.reown.com/appkit/upgrade/to-reown-appkit-web#web3modal-v5-to-reown-appkit---web--wagmi

**Comment by rtomas** [comment]
thanks for the advice !
https://github.com/reown-com/reown-docs/pull/184
