### ISSUE TITLE
[bug]  Project Id can be visible in the network section

### ISSUE THREAD

**Issue by NufailIsmath** [reown-com/appkit#3398]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi/

### Bug Description

The projectId passed through the query parameter in the network request is visible in the Network tab of the browser's developer tools. This could potentially expose sensitive information or internal identifiers, which may lead to security concerns.

### Steps to Reproduce

1. Open the application in a browser.

2. Connect your wallet using reown

3. Open the browser’s Developer Tools (e.g., Chrome: F12 or Ctrl+Shift+I) and go to the Network tab.

5. Observe the network requests being made.

6. Look for the request containing the projectId in the query parameters.

![image](https://github.com/user-attachments/assets/f79d28bf-50d1-4d00-9d27-5bb2a02ed45a)

### Environment

* Browser: Brave
* Operating System: Windows 11
* Client: NextJS

### List of related npm package versions

@reown/appkit/react

### Node.js Version

v22.2.0

### Package Manager

npm@10.7.0

**Comment by rtomas** [comment]
hi @NufailIsmath .. it's not a bug ... 
People should Setup and Verify theirs Domains in order to use it online into http://cloud.reown.com
