### ISSUE TITLE
 Help Needed with Invalid Certificate Issue

### ISSUE THREAD

**Issue by Mouneeswar-Medepally** [reown-com/appkit#3435]
### Link to minimal reproducible example

https://api.web3modal.org/getWallets

### Summary

Hi Team,

I’m encountering an invalid certificate issue when trying to access:
https://api.web3modal.org/getWallets.

Could someone please look into this as soon as possible?

Thanks!

### List of related npm package versions

"@reown/appkit": "^1.5.3",
"@reown/appkit-adapter-solana": "^1.5.3",
"@reown/appkit-adapter-wagmi": "^1.5.3",

### Node.js Version

v20.5.1

### Package Manager

npm@9.8.0

**Comment by arein** [comment]
Please provide proper repro steps

**Comment by Mouneeswar-Medepally** [comment]
[https://appkit-lab.reown.com/library/wagmi/](url)

I'm encountering this issue with the Reown documentation demo version too:
Here’s a screenshot of the problem:

![image](https://github.com/user-attachments/assets/26f1ee7e-996a-4123-9df9-67ab359075b8)

This issue also occurs in my project. Below is my configuration:

`
/* Config.js */
import { createAppKit } from '@reown/appkit/react'
import { mainnet, polygon } from '@reown/appkit/networks'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
const projectId = import.meta.env.VITE_WALLET_ID

export const wagmiNetworks = [mainnet, polygon]
const metadata = {
  name: 'AppKit',
  description: 'AppKit Example',
  url: 'https://example.com', // origin must match your domain & subdomain
  icons: ['https://avatars.githubusercontent.com/u/179229932']
}
export const wagmiAdapter = new WagmiAdapter({
  networks: wagmiNetworks,
  projectId,
  ssr: true
})


createAppKit({
  adapters: [wagmiAdapter],
  networks: wagmiNetworks,
  projectId,
  metadata,
  features: {
    analytics: false,
    socials: [],
    email: false
  },
  themeMode: 'dark',
  themeVariables: {
    "--w3m-z-index": 1999,
  }
})

/*Index.js*/
import { WagmiProvider } from 'wagmi'
import { wagmiAdapter } from './config'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const Wagmi = ({children}) => {
  const queryClient = new QueryClient()
  return (
    <WagmiProvider config={wagmiAdapter.wagmiConfig} reconnectOnMount={false}>
      <QueryClientProvider client={queryClient}>
      {children}
      </QueryClientProvider>
    </WagmiProvider>
  )
}

export default Wagmi
`

please let me know if you need any other information
