### ISSUE TITLE
Invalid Certificate Issue

### ISSUE THREAD

**Issue by Mouneeswar-Medepally** [reown-com/appkit#3445]
### Link to minimal reproducible example

https://github.com/Mouneeswar-Medepally/Appkit_example/tree/main

### Summary

[https://appkit-lab.reown.com/library/wagmi/](https://github.com/reown-com/appkit/issues/url)

I'm encountering this issue with the Reown documentation demo version too:
Here’s a screenshot of the problem:

![image](https://github.com/user-attachments/assets/d53e7596-649d-4bc3-bc20-382595992c25)

This issue also occurs in my project. Below is my configuration:

`
/* Config.js */
import { createAppKit } from '@reown/appkit/react'
import { mainnet, polygon } from '@reown/appkit/networks'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
const projectId = import.meta.env.VITE_WALLET_ID

export const wagmiNetworks = [mainnet, polygon]
const metadata = {
name: 'AppKit',
description: 'AppKit Example',
url: 'https://example.com/', // origin must match your domain & subdomain
icons: ['https://avatars.githubusercontent.com/u/179229932']
}
export const wagmiAdapter = new WagmiAdapter({
networks: wagmiNetworks,
projectId,
ssr: true
})

createAppKit({
adapters: [wagmiAdapter],
networks: wagmiNetworks,
projectId,
metadata,
features: {
analytics: false,
socials: [],
email: false
},
themeMode: 'dark',
themeVariables: {
"--w3m-z-index": 1999,
}
})

/Index.js/
import { WagmiProvider } from 'wagmi'
import { wagmiAdapter } from './config'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const Wagmi = ({children}) => {
const queryClient = new QueryClient()
return (

{children}

)
}

export default Wagmi
`

please let me know if you need any other information

### List of related npm package versions

"@reown/appkit": "^1.5.3",
"@reown/appkit-adapter-solana": "^1.5.3",
"@reown/appkit-adapter-wagmi": "^1.5.3",
"viem": "^2.21.52",
"wagmi": "^2.13.2",

### Node.js Version

v20.5.1

### Package Manager

npm@9.8.0

**Comment by arein** [comment]
@Mouneeswar-Medepally works fine for me? what browser are you using? does it work on your phone?

<img width="1711" alt="Screenshot 2024-12-12 at 12 42 28 PM" src="https://github.com/user-attachments/assets/bbadec3d-51c3-449e-a548-0b0cd7d4b23e" />

**Comment by Mouneeswar-Medepally** [comment]
@arein Yes, It is working fine in my mobile 

It might be because of the security firewalls set up in our office.

Is it really that risky?
