### ISSUE TITLE
[docs] Inconsistency in appkit version between npm and github

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3470]
### Summary

![image](https://github.com/user-attachments/assets/e3f30453-8d3a-485f-a8de-5c40f0c7286a)
![image](https://github.com/user-attachments/assets/65cd0db6-cced-4120-91c9-e07d09626cbc)

### Link to the related docs page

https://github.com/reown-com/appkit

**Comment by Sam-Newman** [comment]
Thanks for raising - we will look into it!

**Comment by arein** [comment]
We're aware of this - will fix soon
