### ISSUE TITLE
[bug] Undefined wallet login in Nova wallet browser

### ISSUE THREAD

**Issue by noahjoeris** [reown-com/appkit#3473]
### Link to minimal reproducible example

https://app.turtle.cool

### Summary

Reproduce:
Open https://app.turtle.cool inside the nova embedded browser. Connect Ethereum wallet. Undefined popup should appear.
See the video below for a demo (popup at 25s).
https://github.com/user-attachments/assets/e1fcaf57-d600-4e3a-9369-28d22afa207b

Info:
- It seems to happen only inside the nova browser.
- Disconnecting and connecting again make it work.
- This console error might be related:
![image](https://github.com/user-attachments/assets/cf3a04fa-da0c-46a2-9ae8-55d4cd38008c)

### List of related npm package versions

 "@reown/appkit": "^1.5.3",
 "@reown/appkit-adapter-wagmi": "^1.5.3",
 "wagmi": "^2.13.3",

### Node.js Version

v20.10.0

### Package Manager

pnpm@9.12.1

**Comment by Sam-Newman** [comment]
Thanks for reporting - we will pick this up!

**Comment by rtomas** [comment]
This is a duplicate bug ... please confirm that the functionality is working ok and it's just the error ...

**Comment by arein** [comment]
I believe we fixed this in 1.6.0 - thanks for reporting - btw @noahjoeris https://app.turtle.cool/ is loading very slowly for me - maybe the background image is too large

**Comment by noahjoeris** [comment]
Thanks a lot for the help. Upgrading to 1.6.0 fixed it 👍 Also appreciate letting us know of the performance issues, we are aware of this and working on a fix :)

**Comment by noahjoeris** [comment]
@arein FYI after updating we now receive a new error. But it doesn't impact the functionality fortunately.
<img width="701" alt="image" src="https://github.com/user-attachments/assets/0c2394b6-5c22-4dd8-8a05-3a34e3f59985" />
<img width="361" alt="image" src="https://github.com/user-attachments/assets/ccd7461c-efdc-4d92-9cc8-67070384adca" />

It happens when connecting an ethereum wallet and then reloading the page. So maybe some persistence issue.

**Comment by rtomas** [comment]
hi @noahjoeris ! Closing the issue. please open a new one for the new error
