### ISSUE TITLE
[bug] wagmiAdapter - connector undefined

### ISSUE THREAD

**Issue by Victor-Salomon** [reown-com/appkit#3497]
### Link to minimal reproducible example

app.turtle.cool

### Summary

After updating to the 1.6.0 to fix [this following error](https://github.com/reown-com/appkit/issues/3473) we now receive new errors when connecting an ethereum wallet and then reloading the page. So maybe some persistence issue.

![image](https://github.com/user-attachments/assets/3bdfa201-89b5-4004-952d-278998854f17)
![image](https://github.com/user-attachments/assets/39455287-5e3e-4c1c-9538-ffb5583fda46)

<img width="971" alt="image" src="https://github.com/user-attachments/assets/11ed24b1-6b13-44ad-a607-13925e259a42" />
<img width="747" alt="image" src="https://github.com/user-attachments/assets/c53a1638-4fb4-4dcd-9300-f1e8d8a09628" />

Reproduce:

Open app.turtle.cool and open the console.
Connect Ethereum wallet.
Reload the page. 
(Eventually, disconnect and start the process again or reload as it seems to appear randomly). 

Thanks for the support.

### List of related npm package versions

"@reown/appkit": "^1.6.0",
"@reown/appkit-adapter-wagmi": "^1.6.0",
"wagmi": "^2.13.3",

### Node.js Version

v20.11.0

### Package Manager

pnpm@9.3.0

**Comment by arein** [comment]
thanks @Victor-Salomon - we'll get around to fixing this soon ! also we released 1.6.1 today which has a lot of improvements - it might already be fixed - mind quickly upgrading?

**Comment by Victor-Salomon** [comment]
Hey @arein,
The 1.6.1 version fixes the two issues mentioned! 
We can consider this issue as fixed.
I'll be back to you if needed.  
Thanks for the support!

**Comment by arein** [comment]
No. Thank you @Victor-Salomon !
