### ISSUE TITLE
[bug] Property 'w3m-button' does not exist on type 'JSX.IntrinsicElements'.

### ISSUE THREAD

**Issue by GGdag63** [reown-com/appkit#3510]
### Link to minimal reproducible example

https://github.com/GGdag63/demokit

### Summary

İ use next.js and i cant run bild for this.can you help me . İ share my github repo 

### List of related npm package versions

Last version for everything

### Node.js Version

v18

### Package Manager

nmp@9.6.7

**Comment by rtomas** [comment]
it's working ok for me
<img width="525" alt="image" src="https://github.com/user-attachments/assets/fbece185-272b-4b84-b365-917824516040" />

**Comment by GGdag63** [comment]
> it's working ok for me <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/944960/397823609-fbece185-272b-4b84-b365-917824516040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjAzMjYsIm5iZiI6MTczNDcyMDAyNiwicGF0aCI6Ii85NDQ5NjAvMzk3ODIzNjA5LWZiZWNlMTg1LTI3MmItNGI4NC1iMzY1LTkxNzgyNDUxNjA0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxODQwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWI3N2I0MzE3ODg3ZGMyM2MwODE4ODBmYWUzZjMwOTdlMTg4ZjU5MGVjNmI4YjE3NjNkNGQ3MGIyYmNlMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I-TSX-EBNOd9CLGa5TbGAeJR_jFpzTdQEsckOrG3mCs">

no it is not work i cant run build 
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true, 
  },
};

export default nextConfig;
 i will use this for run build but now i cant connect in mobile.it is connect and after disconnect immediately.what i am doing wrong please help me .please contact me in discord. hakosta this is my discord username
