### ISSUE TITLE
[bug] Mobile Wallet Login State Lost After Refresh in Vue-Wagmi Example

### ISSUE THREAD

**Issue by frmachao** [reown-com/appkit#3517]
### Link to minimal reproducible example

https://github.com/reown-com/appkit/tree/main/examples/vue-wagmi

### Summary

When using AppKit with the vue-wagmi integration, I encounter an issue where the login state disappears after refreshing the DApp. This happens specifically when a mobile wallet (e.g., scanning a QR code for login) is used to connect.

### Steps to Reproduce

Clone the AppKit repository and navigate to the examples/vue-wagmi directory.
Follow the setup instructions and run the example locally.
Connect to the DApp using a mobile wallet by scanning the QR code.
Refresh the browser.
Observe that the wallet login state is lost after the refresh.

### Screenshots

https://github.com/user-attachments/assets/67002b40-a003-4991-99ea-dbe12890dd58

### List of related npm package versions

    "@reown/appkit": "^1.6.1",
    "@reown/appkit-adapter-wagmi": "^1.6.1",
    "@tanstack/vue-query": "5.59.16",
    "@wagmi/connectors": "5.1.15",
    "@wagmi/core": "2.13.8",
    "@wagmi/vue": "0.0.56",
    "viem": "2.21.26",
    "vue": "3.4.3"

### Node.js Version

v23.0.0

### Package Manager

npm@10.9.0

**Comment by rtomas** [comment]
I cannot reproduce it in our latest examples
https://github.com/reown-com/appkit-web-examples/tree/main/vue/vue-wagmi
