### ISSUE TITLE
[feature] nuxt3 how to use?

### ISSUE THREAD

**Issue by far310** [reown-com/appkit#3551]
### What problem does this new feature solve?

nuxt3 how to use?
Can you give me an example?

### Describe the solution you'd like

I want to use this library in nuxt

**Comment by far310** [comment]
> please check this example -> https://github.com/rtomas/appkit-nuxt-wagmi-example
> 
> We will be adding an example soon to our repocitory

Hey bro, it's not ssr reown-appkit isn't nuxt can't use ssr, I want to be like nextjs

**Comment by far310** [comment]
> please check this example -> https://github.com/rtomas/appkit-nuxt-wagmi-example
> 
> We will be adding an example soon to our repocitory

Can you give me some advice

**Comment by rtomas** [comment]
Do you have a minimal example of your work and please share with me what are you expecting with nuxt + appkit?

**Comment by rtomas** [comment]
And the example I sent to you is wrong ?

**Comment by far310** [comment]
> And the example I sent to you is wrong ?
It's right, but it's not the set ssr.
