### ISSUE TITLE
Sample implementation not working in safari 14

### ISSUE THREAD

**Issue by sibizulu** [reown-com/appkit#663]
**Describe the bug**
Sample implementation not working in safari. 

**To Reproduce**
1. Go to safari and open  'https://web3modal.com/try-it-out'
2. Click on 'Connect  Wallet'
3. Click on any wallet option
4. See nothing showing there

**Expected behavior**
Need to show the option details

**Screenshots**
<img width="1399" alt="Screenshot 2022-10-30 at 9 33 32 AM" src="https://user-images.githubusercontent.com/1639616/198862134-f3f001e4-6c1b-4aca-9b7c-a9bfc83b5709.png">

**Desktop (please complete the following information):**
 - Browser safari

**Comment by IljaDaderko** [comment]
@sibizulu which macOS / safari version is this happening on? I was not able to replicate (I see all default fallback views).

The only issues I see are around doc website css

**Comment by IljaDaderko** [comment]
https://user-images.githubusercontent.com/3154053/198869179-0a4cc6fa-4e87-4d88-a32e-6b06a008b0cb.mov
This is what I am getting in safari `16.1`

Note: Metamask / some other browser extensions don't support safari, so main method of connecting is via mobile. We are working on ui refresh for the modal that takes this into account.

**Comment by sibizulu** [comment]
@IljaDaderko 

Thanks for looking into the issue. I just looking with Macbook Air (M1).

**Comment by sibizulu** [comment]
Also got an error in console when i click any wallet option

`TypeError: undefined is not an object (evaluating 't.borderBoxSize[0]')`

**Comment by IljaDaderko** [comment]
@sibizulu this issue was fixed as part of ios 15 support, here is preview https://47d7584d.web3modal-dev.pages.dev Do you still see any issues here?

**Comment by IljaDaderko** [comment]
Just tested this in latest safari 14 release line, everything seems to work as expected.
