### ISSUE TITLE
Customise modal's z-index

### ISSUE THREAD

**Issue by rick20220222** [reown-com/appkit#784]
I need to set the level of the popover. How do I handle that

**Comment by ganchoradkov** [comment]
moving the issue to the appropriate repo.

Please check the `Theme options` in our docs
https://docs.walletconnect.com/2.0/web3modal/configuration#theming-options

**Comment by rick20220222** [comment]
I checked the documentation, but there are only 3 properties to set 
(thememode-optional、themecolor-optional、themebackground-optional)

**Comment by ganchoradkov** [comment]
cc @0xAsimetriq

**Comment by 0xAsimetriq** [comment]
Next release will include new theme option for this `themeZIndex `
