### ISSUE TITLE
explorerDenyList / explorerAllowList not working [bug] 

### ISSUE THREAD

**Issue by nakshatrasinghh** [reown-com/appkit#962]
### Link to minimal reproducible example

<Web3Modal         projectId={projectId}         ethereumClient={ethereumClient}         explorerAllowList={[           "4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0",         ]}       />

### Summary

explorerDenyList / explorerAllowList options method in web3Modal does not work, in both V1 and V2

### List of related npm package versions

"@wagmi/core": "^0.10.6",
    "@web3modal/ethereum": "^2.2.2",
    "@web3modal/react": "^2.2.2",
    "ethers": "^5.7.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "wagmi": "^0.12.6",

**Comment by 0xAsimetriq** [comment]
Hey 👋

Just tried to reproduce in this example https://github.com/WalletConnect/web3modal/blob/V2/laboratory/src/pages/v1Base.tsx

Seems to be working. What issue are you facing on your end? 

https://user-images.githubusercontent.com/3154053/228553009-51b025b3-9a60-4c9a-b6f2-652ebe60e653.mov

**Comment by nakshatrasinghh** [comment]
c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96, metamask does not seem to work
