### ISSUE TITLE
[bug] Invalid QR Code WalletConnect v2.0 Android

### ISSUE THREAD

**Issue by ntoine223** [reown-com/appkit#964]
### Link to minimal reproducible example

https://lab.web3modal.com/v2Base

### Summary

Hello to everyone,

I have developed a simple online application under an https domain allowing a user to connect with WalletConnect using its version 2 with the [standalone configuration](https://docs.walletconnect.com/2.0/web3modal/standalone/installation).

When I try my application on desktop I have the modal that appears correctly. I can then scan the QR code with an **Android** or **iOS** phone and connect with [a wallet compatible with V2](https://explorer.walletconnect.com/?type=wallet&version=2) (I use Trust or Spot)

When I try my app from a browser on **iOS** and **iPadOS**, I can select my wallet, I am redirected correctly and I can connect correctly.

However, when I try the same manipulation from a browser on **Android**, I can select my wallet, I am redirected properly BUT I get an error message telling me:

> Invalid QR Code WalletConnect.

I tested this with several **Android** phones and tablets, with several browsers, but I get the same error every time.

[Photo here](https://i.stack.imgur.com/LmG9M.png)

Is there an explanation for this behavior? Knowing that the v2 of walletconnect is from what I understand still in migration.

Note that I have the same behavior on the **Walletconnect examples** on this page: https://lab.web3modal.com/ for version 2 but not for version 1.

### List of related npm package versions

 - @walletconnect/sign-client: ^2.3.3
 - @web3modal/standalone : ^2.2.2
 - react : ^17.0.2
 - react-dom : ^17.0.2

**Comment by 0xAsimetriq** [comment]
There is no actionable reproduction provided to help us debug this (linking back to modal lab is not helpful I'm afraid). Could you open another issue that includes code of your dapp / live deployment that we can test to get an idea of what could be wrong?

Meanwhile, I tried connecting to v2Base lab example on my android phone, everything seems to work as expected as per video below:

https://user-images.githubusercontent.com/3154053/228824292-ff71875d-19a5-45c4-8852-6db9f4985b0c.mp4

Closing this issue meanwhile, will be waiting for new one with reproduction examples.
